/* File: ormodelmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Aug 14 11:59:45 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *ormodel_error;
static PyObject *ormodel_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(ormodel_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = ormodel_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = ormodel_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(compute,COMPUTE)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** compute **********************************/
static char doc_f2py_rout_ormodel_compute[] = "\
pyrain = compute(pyelev,pydx,pywindx,pywindy,pyminrain,pymaxrain,pybackrain,pynm,pycw,pyhw,pytauc,pytauf,[pynx,pyny])\n\nWrapper for ``compute``.\
\n\nParameters\n----------\n"
"pyelev : input rank-2 array('f') with bounds (pynx,pyny)\n"
"pydx : input float\n"
"pywindx : input float\n"
"pywindy : input float\n"
"pyminrain : input float\n"
"pymaxrain : input float\n"
"pybackrain : input float\n"
"pynm : input float\n"
"pycw : input float\n"
"pyhw : input float\n"
"pytauc : input float\n"
"pytauf : input float\n"
"\nOther Parameters\n----------------\n"
"pynx : input int, optional\n    Default: shape(pyelev,0)\n"
"pyny : input int, optional\n    Default: shape(pyelev,1)\n"
"\nReturns\n-------\n"
"pyrain : rank-2 array('f') with bounds (pynx,pyny)";
/* extern void F_FUNC(compute,COMPUTE)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*,int*); */
static PyObject *f2py_rout_ormodel_compute(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *pyelev = NULL;
  npy_intp pyelev_Dims[2] = {-1, -1};
  const int pyelev_Rank = 2;
  PyArrayObject *capi_pyelev_tmp = NULL;
  int capi_pyelev_intent = 0;
  PyObject *pyelev_capi = Py_None;
  float pydx = 0;
  PyObject *pydx_capi = Py_None;
  float pywindx = 0;
  PyObject *pywindx_capi = Py_None;
  float pywindy = 0;
  PyObject *pywindy_capi = Py_None;
  float pyminrain = 0;
  PyObject *pyminrain_capi = Py_None;
  float pymaxrain = 0;
  PyObject *pymaxrain_capi = Py_None;
  float pybackrain = 0;
  PyObject *pybackrain_capi = Py_None;
  float pynm = 0;
  PyObject *pynm_capi = Py_None;
  float pycw = 0;
  PyObject *pycw_capi = Py_None;
  float pyhw = 0;
  PyObject *pyhw_capi = Py_None;
  float pytauc = 0;
  PyObject *pytauc_capi = Py_None;
  float pytauf = 0;
  PyObject *pytauf_capi = Py_None;
  float *pyrain = NULL;
  npy_intp pyrain_Dims[2] = {-1, -1};
  const int pyrain_Rank = 2;
  PyArrayObject *capi_pyrain_tmp = NULL;
  int capi_pyrain_intent = 0;
  int pynx = 0;
  PyObject *pynx_capi = Py_None;
  int pyny = 0;
  PyObject *pyny_capi = Py_None;
  static char *capi_kwlist[] = {"pyelev","pydx","pywindx","pywindy","pyminrain","pymaxrain","pybackrain","pynm","pycw","pyhw","pytauc","pytauf","pynx","pyny",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOO|OO:ormodel.compute",\
    capi_kwlist,&pyelev_capi,&pydx_capi,&pywindx_capi,&pywindy_capi,&pyminrain_capi,&pymaxrain_capi,&pybackrain_capi,&pynm_capi,&pycw_capi,&pyhw_capi,&pytauc_capi,&pytauf_capi,&pynx_capi,&pyny_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pydx */
    f2py_success = float_from_pyobj(&pydx,pydx_capi,"ormodel.compute() 2nd argument (pydx) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pymaxrain */
    f2py_success = float_from_pyobj(&pymaxrain,pymaxrain_capi,"ormodel.compute() 6th argument (pymaxrain) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pynm */
    f2py_success = float_from_pyobj(&pynm,pynm_capi,"ormodel.compute() 8th argument (pynm) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pyhw */
    f2py_success = float_from_pyobj(&pyhw,pyhw_capi,"ormodel.compute() 10th argument (pyhw) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pytauf */
    f2py_success = float_from_pyobj(&pytauf,pytauf_capi,"ormodel.compute() 12nd argument (pytauf) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pywindx */
    f2py_success = float_from_pyobj(&pywindx,pywindx_capi,"ormodel.compute() 3rd argument (pywindx) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pyelev */
  ;
  capi_pyelev_intent |= F2PY_INTENT_IN;
  capi_pyelev_tmp = array_from_pyobj(NPY_FLOAT,pyelev_Dims,pyelev_Rank,capi_pyelev_intent,pyelev_capi);
  if (capi_pyelev_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ormodel_error,"failed in converting 1st argument `pyelev' of ormodel.compute to C/Fortran array" );
  } else {
    pyelev = (float *)(PyArray_DATA(capi_pyelev_tmp));

  /* Processing variable pyminrain */
    f2py_success = float_from_pyobj(&pyminrain,pyminrain_capi,"ormodel.compute() 5th argument (pyminrain) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pywindy */
    f2py_success = float_from_pyobj(&pywindy,pywindy_capi,"ormodel.compute() 4th argument (pywindy) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pycw */
    f2py_success = float_from_pyobj(&pycw,pycw_capi,"ormodel.compute() 9th argument (pycw) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pytauc */
    f2py_success = float_from_pyobj(&pytauc,pytauc_capi,"ormodel.compute() 11st argument (pytauc) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pybackrain */
    f2py_success = float_from_pyobj(&pybackrain,pybackrain_capi,"ormodel.compute() 7th argument (pybackrain) can't be converted to float");
  if (f2py_success) {
  /* Processing variable pyny */
  if (pyny_capi == Py_None) pyny = shape(pyelev,1); else
    f2py_success = int_from_pyobj(&pyny,pyny_capi,"ormodel.compute() 2nd keyword (pyny) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pyelev,1)==pyny,"shape(pyelev,1)==pyny","2nd keyword pyny","compute:pyny=%d",pyny) {
  /* Processing variable pynx */
  if (pynx_capi == Py_None) pynx = shape(pyelev,0); else
    f2py_success = int_from_pyobj(&pynx,pynx_capi,"ormodel.compute() 1st keyword (pynx) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pyelev,0)==pynx,"shape(pyelev,0)==pynx","1st keyword pynx","compute:pynx=%d",pynx) {
  /* Processing variable pyrain */
  pyrain_Dims[0]=pynx,pyrain_Dims[1]=pyny;
  capi_pyrain_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_pyrain_tmp = array_from_pyobj(NPY_FLOAT,pyrain_Dims,pyrain_Rank,capi_pyrain_intent,Py_None);
  if (capi_pyrain_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ormodel_error,"failed in converting hidden `pyrain' of ormodel.compute to C/Fortran array" );
  } else {
    pyrain = (float *)(PyArray_DATA(capi_pyrain_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyelev,&pydx,&pywindx,&pywindy,&pyminrain,&pymaxrain,&pybackrain,&pynm,&pycw,&pyhw,&pytauc,&pytauf,pyrain,&pynx,&pyny);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_pyrain_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_pyrain_tmp == NULL) ... else of pyrain*/
  /* End of cleaning variable pyrain */
  } /*CHECKSCALAR(shape(pyelev,0)==pynx)*/
  } /*if (f2py_success) of pynx*/
  /* End of cleaning variable pynx */
  } /*CHECKSCALAR(shape(pyelev,1)==pyny)*/
  } /*if (f2py_success) of pyny*/
  /* End of cleaning variable pyny */
  } /*if (f2py_success) of pybackrain*/
  /* End of cleaning variable pybackrain */
  } /*if (f2py_success) of pytauc*/
  /* End of cleaning variable pytauc */
  } /*if (f2py_success) of pycw*/
  /* End of cleaning variable pycw */
  } /*if (f2py_success) of pywindy*/
  /* End of cleaning variable pywindy */
  } /*if (f2py_success) of pyminrain*/
  /* End of cleaning variable pyminrain */
  if((PyObject *)capi_pyelev_tmp!=pyelev_capi) {
    Py_XDECREF(capi_pyelev_tmp); }
  }  /*if (capi_pyelev_tmp == NULL) ... else of pyelev*/
  /* End of cleaning variable pyelev */
  } /*if (f2py_success) of pywindx*/
  /* End of cleaning variable pywindx */
  } /*if (f2py_success) of pytauf*/
  /* End of cleaning variable pytauf */
  } /*if (f2py_success) of pyhw*/
  /* End of cleaning variable pyhw */
  } /*if (f2py_success) of pynm*/
  /* End of cleaning variable pynm */
  } /*if (f2py_success) of pymaxrain*/
  /* End of cleaning variable pymaxrain */
  } /*if (f2py_success) of pydx*/
  /* End of cleaning variable pydx */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of compute *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"compute",-1,{{-1}},0,(char *)F_FUNC(compute,COMPUTE),(f2py_init_func)f2py_rout_ormodel_compute,doc_f2py_rout_ormodel_compute},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "ormodel",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_ormodel(void) {
#else
#define RETVAL
PyMODINIT_FUNC initormodel(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = ormodel_module = PyModule_Create(&moduledef);
#else
  m = ormodel_module = Py_InitModule("ormodel", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module ormodel (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'ormodel' is auto-generated with f2py (version:2).\nFunctions:\n"
"  pyrain = compute(pyelev,pydx,pywindx,pywindy,pyminrain,pymaxrain,pybackrain,pynm,pycw,pyhw,pytauc,pytauf,pynx=shape(pyelev,0),pyny=shape(pyelev,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  ormodel_error = PyErr_NewException ("ormodel.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"ormodel");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
