/* File: pdalgomodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Aug 14 11:59:45 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *pdalgo_error;
static PyObject *pdalgo_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(pdalgo_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = pdalgo_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = pdalgo_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(marine_distribution,MARINE_DISTRIBUTION)(double*,double*,double*,int*,int*,double*,int*,int*,int*);
extern void F_FUNC(pitparams,PITPARAMS)(int*,double*,int*,double*,double*,double*,int*,int*);
extern void F_FUNC(pitfilling,PITFILLING)(double*,int*,double*,double*,int*);
extern void F_FUNC(getactlay,GETACTLAY)(double*,double*,double*,double*,int*,int*,int*);
extern void F_FUNC(getactlay2,GETACTLAY2)(double*,double*,double*,double*,int*,int*,int*);
extern void F_FUNC(updatestrati,UPDATESTRATI)(double*,double*,double*,double*,double*,double*,int*,int*,int*);
extern void F_FUNC(updatecstrati,UPDATECSTRATI)(double*,double*,double*,double*,double*,double*,int*,int*,int*);
extern void F_FUNC(stratcarb,STRATCARB)(double*,double*,double*,double*,double*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/**************************** marine_distribution ****************************/
static char doc_f2py_rout_pdalgo_marine_distribution[] = "\
diffsed = marine_distribution(elevation,seavol,sealevel,border,depids,[pydnodes,pyids,pyrocknb])\n\nWrapper for ``marine_distribution``.\
\n\nParameters\n----------\n"
"elevation : input rank-1 array('d') with bounds (pydnodes)\n"
"seavol : input rank-2 array('d') with bounds (pydnodes,pyrocknb)\n"
"sealevel : input float\n"
"border : input rank-1 array('i') with bounds (pydnodes)\n"
"depids : input rank-1 array('i') with bounds (pyids)\n"
"\nOther Parameters\n----------------\n"
"pydnodes : input int, optional\n    Default: len(elevation)\n"
"pyids : input int, optional\n    Default: len(depids)\n"
"pyrocknb : input int, optional\n    Default: shape(seavol,1)\n"
"\nReturns\n-------\n"
"diffsed : rank-2 array('d') with bounds (pydnodes,pyrocknb)";
/* extern void F_FUNC_US(marine_distribution,MARINE_DISTRIBUTION)(double*,double*,double*,int*,int*,double*,int*,int*,int*); */
static PyObject *f2py_rout_pdalgo_marine_distribution(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *elevation = NULL;
  npy_intp elevation_Dims[1] = {-1};
  const int elevation_Rank = 1;
  PyArrayObject *capi_elevation_tmp = NULL;
  int capi_elevation_intent = 0;
  PyObject *elevation_capi = Py_None;
  double *seavol = NULL;
  npy_intp seavol_Dims[2] = {-1, -1};
  const int seavol_Rank = 2;
  PyArrayObject *capi_seavol_tmp = NULL;
  int capi_seavol_intent = 0;
  PyObject *seavol_capi = Py_None;
  double sealevel = 0;
  PyObject *sealevel_capi = Py_None;
  int *border = NULL;
  npy_intp border_Dims[1] = {-1};
  const int border_Rank = 1;
  PyArrayObject *capi_border_tmp = NULL;
  int capi_border_intent = 0;
  PyObject *border_capi = Py_None;
  int *depids = NULL;
  npy_intp depids_Dims[1] = {-1};
  const int depids_Rank = 1;
  PyArrayObject *capi_depids_tmp = NULL;
  int capi_depids_intent = 0;
  PyObject *depids_capi = Py_None;
  double *diffsed = NULL;
  npy_intp diffsed_Dims[2] = {-1, -1};
  const int diffsed_Rank = 2;
  PyArrayObject *capi_diffsed_tmp = NULL;
  int capi_diffsed_intent = 0;
  int pydnodes = 0;
  PyObject *pydnodes_capi = Py_None;
  int pyids = 0;
  PyObject *pyids_capi = Py_None;
  int pyrocknb = 0;
  PyObject *pyrocknb_capi = Py_None;
  static char *capi_kwlist[] = {"elevation","seavol","sealevel","border","depids","pydnodes","pyids","pyrocknb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOO:pdalgo.marine_distribution",\
    capi_kwlist,&elevation_capi,&seavol_capi,&sealevel_capi,&border_capi,&depids_capi,&pydnodes_capi,&pyids_capi,&pyrocknb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable depids */
  ;
  capi_depids_intent |= F2PY_INTENT_IN;
  capi_depids_tmp = array_from_pyobj(NPY_INT,depids_Dims,depids_Rank,capi_depids_intent,depids_capi);
  if (capi_depids_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 5th argument `depids' of pdalgo.marine_distribution to C/Fortran array" );
  } else {
    depids = (int *)(PyArray_DATA(capi_depids_tmp));

  /* Processing variable elevation */
  ;
  capi_elevation_intent |= F2PY_INTENT_IN;
  capi_elevation_tmp = array_from_pyobj(NPY_DOUBLE,elevation_Dims,elevation_Rank,capi_elevation_intent,elevation_capi);
  if (capi_elevation_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 1st argument `elevation' of pdalgo.marine_distribution to C/Fortran array" );
  } else {
    elevation = (double *)(PyArray_DATA(capi_elevation_tmp));

  /* Processing variable sealevel */
    f2py_success = double_from_pyobj(&sealevel,sealevel_capi,"pdalgo.marine_distribution() 3rd argument (sealevel) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pyids */
  if (pyids_capi == Py_None) pyids = len(depids); else
    f2py_success = int_from_pyobj(&pyids,pyids_capi,"pdalgo.marine_distribution() 2nd keyword (pyids) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(depids)>=pyids,"len(depids)>=pyids","2nd keyword pyids","marine_distribution:pyids=%d",pyids) {
  /* Processing variable pydnodes */
  if (pydnodes_capi == Py_None) pydnodes = len(elevation); else
    f2py_success = int_from_pyobj(&pydnodes,pydnodes_capi,"pdalgo.marine_distribution() 1st keyword (pydnodes) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(elevation)>=pydnodes,"len(elevation)>=pydnodes","1st keyword pydnodes","marine_distribution:pydnodes=%d",pydnodes) {
  /* Processing variable seavol */
  seavol_Dims[0]=pydnodes;
  capi_seavol_intent |= F2PY_INTENT_IN;
  capi_seavol_tmp = array_from_pyobj(NPY_DOUBLE,seavol_Dims,seavol_Rank,capi_seavol_intent,seavol_capi);
  if (capi_seavol_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 2nd argument `seavol' of pdalgo.marine_distribution to C/Fortran array" );
  } else {
    seavol = (double *)(PyArray_DATA(capi_seavol_tmp));

  /* Processing variable border */
  border_Dims[0]=pydnodes;
  capi_border_intent |= F2PY_INTENT_IN;
  capi_border_tmp = array_from_pyobj(NPY_INT,border_Dims,border_Rank,capi_border_intent,border_capi);
  if (capi_border_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 4th argument `border' of pdalgo.marine_distribution to C/Fortran array" );
  } else {
    border = (int *)(PyArray_DATA(capi_border_tmp));

  /* Processing variable pyrocknb */
  if (pyrocknb_capi == Py_None) pyrocknb = shape(seavol,1); else
    f2py_success = int_from_pyobj(&pyrocknb,pyrocknb_capi,"pdalgo.marine_distribution() 3rd keyword (pyrocknb) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(seavol,1)==pyrocknb,"shape(seavol,1)==pyrocknb","3rd keyword pyrocknb","marine_distribution:pyrocknb=%d",pyrocknb) {
  /* Processing variable diffsed */
  diffsed_Dims[0]=pydnodes,diffsed_Dims[1]=pyrocknb;
  capi_diffsed_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_diffsed_tmp = array_from_pyobj(NPY_DOUBLE,diffsed_Dims,diffsed_Rank,capi_diffsed_intent,Py_None);
  if (capi_diffsed_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `diffsed' of pdalgo.marine_distribution to C/Fortran array" );
  } else {
    diffsed = (double *)(PyArray_DATA(capi_diffsed_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(elevation,seavol,&sealevel,border,depids,diffsed,&pydnodes,&pyids,&pyrocknb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_diffsed_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_diffsed_tmp == NULL) ... else of diffsed*/
  /* End of cleaning variable diffsed */
  } /*CHECKSCALAR(shape(seavol,1)==pyrocknb)*/
  } /*if (f2py_success) of pyrocknb*/
  /* End of cleaning variable pyrocknb */
  if((PyObject *)capi_border_tmp!=border_capi) {
    Py_XDECREF(capi_border_tmp); }
  }  /*if (capi_border_tmp == NULL) ... else of border*/
  /* End of cleaning variable border */
  if((PyObject *)capi_seavol_tmp!=seavol_capi) {
    Py_XDECREF(capi_seavol_tmp); }
  }  /*if (capi_seavol_tmp == NULL) ... else of seavol*/
  /* End of cleaning variable seavol */
  } /*CHECKSCALAR(len(elevation)>=pydnodes)*/
  } /*if (f2py_success) of pydnodes*/
  /* End of cleaning variable pydnodes */
  } /*CHECKSCALAR(len(depids)>=pyids)*/
  } /*if (f2py_success) of pyids*/
  /* End of cleaning variable pyids */
  } /*if (f2py_success) of sealevel*/
  /* End of cleaning variable sealevel */
  if((PyObject *)capi_elevation_tmp!=elevation_capi) {
    Py_XDECREF(capi_elevation_tmp); }
  }  /*if (capi_elevation_tmp == NULL) ... else of elevation*/
  /* End of cleaning variable elevation */
  if((PyObject *)capi_depids_tmp!=depids_capi) {
    Py_XDECREF(capi_depids_tmp); }
  }  /*if (capi_depids_tmp == NULL) ... else of depids*/
  /* End of cleaning variable depids */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of marine_distribution *************************/

/********************************* pitparams *********************************/
static char doc_f2py_rout_pdalgo_pitparams[] = "\
pitparams(pyngbs,pyarea,pydiff,pyprop,fillth,epsilon,pybounds,[pydnodes])\n\nWrapper for ``pitparams``.\
\n\nParameters\n----------\n"
"pyngbs : input rank-2 array('i') with bounds (pydnodes,20)\n"
"pyarea : input rank-1 array('d') with bounds (pydnodes)\n"
"pydiff : input int\n"
"pyprop : input float\n"
"fillth : input float\n"
"epsilon : input float\n"
"pybounds : input int\n"
"\nOther Parameters\n----------------\n"
"pydnodes : input int, optional\n    Default: shape(pyngbs,0)";
/* extern void F_FUNC(pitparams,PITPARAMS)(int*,double*,int*,double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_pdalgo_pitparams(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,double*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int *pyngbs = NULL;
  npy_intp pyngbs_Dims[2] = {-1, -1};
  const int pyngbs_Rank = 2;
  PyArrayObject *capi_pyngbs_tmp = NULL;
  int capi_pyngbs_intent = 0;
  PyObject *pyngbs_capi = Py_None;
  double *pyarea = NULL;
  npy_intp pyarea_Dims[1] = {-1};
  const int pyarea_Rank = 1;
  PyArrayObject *capi_pyarea_tmp = NULL;
  int capi_pyarea_intent = 0;
  PyObject *pyarea_capi = Py_None;
  int pydiff = 0;
  PyObject *pydiff_capi = Py_None;
  double pyprop = 0;
  PyObject *pyprop_capi = Py_None;
  double fillth = 0;
  PyObject *fillth_capi = Py_None;
  double epsilon = 0;
  PyObject *epsilon_capi = Py_None;
  int pybounds = 0;
  PyObject *pybounds_capi = Py_None;
  int pydnodes = 0;
  PyObject *pydnodes_capi = Py_None;
  static char *capi_kwlist[] = {"pyngbs","pyarea","pydiff","pyprop","fillth","epsilon","pybounds","pydnodes",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:pdalgo.pitparams",\
    capi_kwlist,&pyngbs_capi,&pyarea_capi,&pydiff_capi,&pyprop_capi,&fillth_capi,&epsilon_capi,&pybounds_capi,&pydnodes_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pydiff */
    f2py_success = int_from_pyobj(&pydiff,pydiff_capi,"pdalgo.pitparams() 3rd argument (pydiff) can't be converted to int");
  if (f2py_success) {
  /* Processing variable fillth */
    f2py_success = double_from_pyobj(&fillth,fillth_capi,"pdalgo.pitparams() 5th argument (fillth) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pybounds */
    f2py_success = int_from_pyobj(&pybounds,pybounds_capi,"pdalgo.pitparams() 7th argument (pybounds) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyprop */
    f2py_success = double_from_pyobj(&pyprop,pyprop_capi,"pdalgo.pitparams() 4th argument (pyprop) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pyngbs */
  pyngbs_Dims[1]=20;
  capi_pyngbs_intent |= F2PY_INTENT_IN;
  capi_pyngbs_tmp = array_from_pyobj(NPY_INT,pyngbs_Dims,pyngbs_Rank,capi_pyngbs_intent,pyngbs_capi);
  if (capi_pyngbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 1st argument `pyngbs' of pdalgo.pitparams to C/Fortran array" );
  } else {
    pyngbs = (int *)(PyArray_DATA(capi_pyngbs_tmp));

  /* Processing variable epsilon */
    f2py_success = double_from_pyobj(&epsilon,epsilon_capi,"pdalgo.pitparams() 6th argument (epsilon) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pydnodes */
  if (pydnodes_capi == Py_None) pydnodes = shape(pyngbs,0); else
    f2py_success = int_from_pyobj(&pydnodes,pydnodes_capi,"pdalgo.pitparams() 1st keyword (pydnodes) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pyngbs,0)==pydnodes,"shape(pyngbs,0)==pydnodes","1st keyword pydnodes","pitparams:pydnodes=%d",pydnodes) {
  /* Processing variable pyarea */
  pyarea_Dims[0]=pydnodes;
  capi_pyarea_intent |= F2PY_INTENT_IN;
  capi_pyarea_tmp = array_from_pyobj(NPY_DOUBLE,pyarea_Dims,pyarea_Rank,capi_pyarea_intent,pyarea_capi);
  if (capi_pyarea_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 2nd argument `pyarea' of pdalgo.pitparams to C/Fortran array" );
  } else {
    pyarea = (double *)(PyArray_DATA(capi_pyarea_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyngbs,pyarea,&pydiff,&pyprop,&fillth,&epsilon,&pybounds,&pydnodes);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_pyarea_tmp!=pyarea_capi) {
    Py_XDECREF(capi_pyarea_tmp); }
  }  /*if (capi_pyarea_tmp == NULL) ... else of pyarea*/
  /* End of cleaning variable pyarea */
  } /*CHECKSCALAR(shape(pyngbs,0)==pydnodes)*/
  } /*if (f2py_success) of pydnodes*/
  /* End of cleaning variable pydnodes */
  } /*if (f2py_success) of epsilon*/
  /* End of cleaning variable epsilon */
  if((PyObject *)capi_pyngbs_tmp!=pyngbs_capi) {
    Py_XDECREF(capi_pyngbs_tmp); }
  }  /*if (capi_pyngbs_tmp == NULL) ... else of pyngbs*/
  /* End of cleaning variable pyngbs */
  } /*if (f2py_success) of pyprop*/
  /* End of cleaning variable pyprop */
  } /*if (f2py_success) of pybounds*/
  /* End of cleaning variable pybounds */
  } /*if (f2py_success) of fillth*/
  /* End of cleaning variable fillth */
  } /*if (f2py_success) of pydiff*/
  /* End of cleaning variable pydiff */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of pitparams ******************************/

/********************************* pitfilling *********************************/
static char doc_f2py_rout_pdalgo_pitfilling[] = "\
demh = pitfilling(elevation,allfill,sealevel,[pydnodes])\n\nWrapper for ``pitfilling``.\
\n\nParameters\n----------\n"
"elevation : input rank-1 array('d') with bounds (pydnodes)\n"
"allfill : input int\n"
"sealevel : input float\n"
"\nOther Parameters\n----------------\n"
"pydnodes : input int, optional\n    Default: len(elevation)\n"
"\nReturns\n-------\n"
"demh : rank-1 array('d') with bounds (pydnodes)";
/* extern void F_FUNC(pitfilling,PITFILLING)(double*,int*,double*,double*,int*); */
static PyObject *f2py_rout_pdalgo_pitfilling(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *elevation = NULL;
  npy_intp elevation_Dims[1] = {-1};
  const int elevation_Rank = 1;
  PyArrayObject *capi_elevation_tmp = NULL;
  int capi_elevation_intent = 0;
  PyObject *elevation_capi = Py_None;
  int allfill = 0;
  PyObject *allfill_capi = Py_None;
  double sealevel = 0;
  PyObject *sealevel_capi = Py_None;
  double *demh = NULL;
  npy_intp demh_Dims[1] = {-1};
  const int demh_Rank = 1;
  PyArrayObject *capi_demh_tmp = NULL;
  int capi_demh_intent = 0;
  int pydnodes = 0;
  PyObject *pydnodes_capi = Py_None;
  static char *capi_kwlist[] = {"elevation","allfill","sealevel","pydnodes",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:pdalgo.pitfilling",\
    capi_kwlist,&elevation_capi,&allfill_capi,&sealevel_capi,&pydnodes_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable allfill */
    f2py_success = int_from_pyobj(&allfill,allfill_capi,"pdalgo.pitfilling() 2nd argument (allfill) can't be converted to int");
  if (f2py_success) {
  /* Processing variable elevation */
  ;
  capi_elevation_intent |= F2PY_INTENT_IN;
  capi_elevation_tmp = array_from_pyobj(NPY_DOUBLE,elevation_Dims,elevation_Rank,capi_elevation_intent,elevation_capi);
  if (capi_elevation_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 1st argument `elevation' of pdalgo.pitfilling to C/Fortran array" );
  } else {
    elevation = (double *)(PyArray_DATA(capi_elevation_tmp));

  /* Processing variable sealevel */
    f2py_success = double_from_pyobj(&sealevel,sealevel_capi,"pdalgo.pitfilling() 3rd argument (sealevel) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pydnodes */
  if (pydnodes_capi == Py_None) pydnodes = len(elevation); else
    f2py_success = int_from_pyobj(&pydnodes,pydnodes_capi,"pdalgo.pitfilling() 1st keyword (pydnodes) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(elevation)>=pydnodes,"len(elevation)>=pydnodes","1st keyword pydnodes","pitfilling:pydnodes=%d",pydnodes) {
  /* Processing variable demh */
  demh_Dims[0]=pydnodes;
  capi_demh_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_demh_tmp = array_from_pyobj(NPY_DOUBLE,demh_Dims,demh_Rank,capi_demh_intent,Py_None);
  if (capi_demh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `demh' of pdalgo.pitfilling to C/Fortran array" );
  } else {
    demh = (double *)(PyArray_DATA(capi_demh_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(elevation,&allfill,&sealevel,demh,&pydnodes);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_demh_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_demh_tmp == NULL) ... else of demh*/
  /* End of cleaning variable demh */
  } /*CHECKSCALAR(len(elevation)>=pydnodes)*/
  } /*if (f2py_success) of pydnodes*/
  /* End of cleaning variable pydnodes */
  } /*if (f2py_success) of sealevel*/
  /* End of cleaning variable sealevel */
  if((PyObject *)capi_elevation_tmp!=elevation_capi) {
    Py_XDECREF(capi_elevation_tmp); }
  }  /*if (capi_elevation_tmp == NULL) ... else of elevation*/
  /* End of cleaning variable elevation */
  } /*if (f2py_success) of allfill*/
  /* End of cleaning variable allfill */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of pitfilling *****************************/

/********************************* getactlay *********************************/
static char doc_f2py_rout_pdalgo_getactlay[] = "\
alays = getactlay(alay,layth,laysd,[nbpts,nblay,nbsed])\n\nWrapper for ``getactlay``.\
\n\nParameters\n----------\n"
"alay : input rank-1 array('d') with bounds (nbpts)\n"
"layth : input rank-2 array('d') with bounds (nbpts,nblay)\n"
"laysd : input rank-3 array('d') with bounds (nbpts,nblay,nbsed)\n"
"\nOther Parameters\n----------------\n"
"nbpts : input int, optional\n    Default: len(alay)\n"
"nblay : input int, optional\n    Default: shape(layth,1)\n"
"nbsed : input int, optional\n    Default: shape(laysd,2)\n"
"\nReturns\n-------\n"
"alays : rank-2 array('d') with bounds (nbpts,nbsed)";
/* extern void F_FUNC(getactlay,GETACTLAY)(double*,double*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_pdalgo_getactlay(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *alay = NULL;
  npy_intp alay_Dims[1] = {-1};
  const int alay_Rank = 1;
  PyArrayObject *capi_alay_tmp = NULL;
  int capi_alay_intent = 0;
  PyObject *alay_capi = Py_None;
  double *layth = NULL;
  npy_intp layth_Dims[2] = {-1, -1};
  const int layth_Rank = 2;
  PyArrayObject *capi_layth_tmp = NULL;
  int capi_layth_intent = 0;
  PyObject *layth_capi = Py_None;
  double *laysd = NULL;
  npy_intp laysd_Dims[3] = {-1, -1, -1};
  const int laysd_Rank = 3;
  PyArrayObject *capi_laysd_tmp = NULL;
  int capi_laysd_intent = 0;
  PyObject *laysd_capi = Py_None;
  double *alays = NULL;
  npy_intp alays_Dims[2] = {-1, -1};
  const int alays_Rank = 2;
  PyArrayObject *capi_alays_tmp = NULL;
  int capi_alays_intent = 0;
  int nbpts = 0;
  PyObject *nbpts_capi = Py_None;
  int nblay = 0;
  PyObject *nblay_capi = Py_None;
  int nbsed = 0;
  PyObject *nbsed_capi = Py_None;
  static char *capi_kwlist[] = {"alay","layth","laysd","nbpts","nblay","nbsed",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOO:pdalgo.getactlay",\
    capi_kwlist,&alay_capi,&layth_capi,&laysd_capi,&nbpts_capi,&nblay_capi,&nbsed_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable alay */
  ;
  capi_alay_intent |= F2PY_INTENT_IN;
  capi_alay_tmp = array_from_pyobj(NPY_DOUBLE,alay_Dims,alay_Rank,capi_alay_intent,alay_capi);
  if (capi_alay_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 1st argument `alay' of pdalgo.getactlay to C/Fortran array" );
  } else {
    alay = (double *)(PyArray_DATA(capi_alay_tmp));

  /* Processing variable nbpts */
  if (nbpts_capi == Py_None) nbpts = len(alay); else
    f2py_success = int_from_pyobj(&nbpts,nbpts_capi,"pdalgo.getactlay() 1st keyword (nbpts) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(alay)>=nbpts,"len(alay)>=nbpts","1st keyword nbpts","getactlay:nbpts=%d",nbpts) {
  /* Processing variable layth */
  layth_Dims[0]=nbpts;
  capi_layth_intent |= F2PY_INTENT_IN;
  capi_layth_tmp = array_from_pyobj(NPY_DOUBLE,layth_Dims,layth_Rank,capi_layth_intent,layth_capi);
  if (capi_layth_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 2nd argument `layth' of pdalgo.getactlay to C/Fortran array" );
  } else {
    layth = (double *)(PyArray_DATA(capi_layth_tmp));

  /* Processing variable nblay */
  if (nblay_capi == Py_None) nblay = shape(layth,1); else
    f2py_success = int_from_pyobj(&nblay,nblay_capi,"pdalgo.getactlay() 2nd keyword (nblay) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(layth,1)==nblay,"shape(layth,1)==nblay","2nd keyword nblay","getactlay:nblay=%d",nblay) {
  /* Processing variable laysd */
  laysd_Dims[0]=nbpts,laysd_Dims[1]=nblay;
  capi_laysd_intent |= F2PY_INTENT_IN;
  capi_laysd_tmp = array_from_pyobj(NPY_DOUBLE,laysd_Dims,laysd_Rank,capi_laysd_intent,laysd_capi);
  if (capi_laysd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 3rd argument `laysd' of pdalgo.getactlay to C/Fortran array" );
  } else {
    laysd = (double *)(PyArray_DATA(capi_laysd_tmp));

  /* Processing variable nbsed */
  if (nbsed_capi == Py_None) nbsed = shape(laysd,2); else
    f2py_success = int_from_pyobj(&nbsed,nbsed_capi,"pdalgo.getactlay() 3rd keyword (nbsed) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(laysd,2)==nbsed,"shape(laysd,2)==nbsed","3rd keyword nbsed","getactlay:nbsed=%d",nbsed) {
  /* Processing variable alays */
  alays_Dims[0]=nbpts,alays_Dims[1]=nbsed;
  capi_alays_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alays_tmp = array_from_pyobj(NPY_DOUBLE,alays_Dims,alays_Rank,capi_alays_intent,Py_None);
  if (capi_alays_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `alays' of pdalgo.getactlay to C/Fortran array" );
  } else {
    alays = (double *)(PyArray_DATA(capi_alays_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(alay,layth,laysd,alays,&nbpts,&nblay,&nbsed);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_alays_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_alays_tmp == NULL) ... else of alays*/
  /* End of cleaning variable alays */
  } /*CHECKSCALAR(shape(laysd,2)==nbsed)*/
  } /*if (f2py_success) of nbsed*/
  /* End of cleaning variable nbsed */
  if((PyObject *)capi_laysd_tmp!=laysd_capi) {
    Py_XDECREF(capi_laysd_tmp); }
  }  /*if (capi_laysd_tmp == NULL) ... else of laysd*/
  /* End of cleaning variable laysd */
  } /*CHECKSCALAR(shape(layth,1)==nblay)*/
  } /*if (f2py_success) of nblay*/
  /* End of cleaning variable nblay */
  if((PyObject *)capi_layth_tmp!=layth_capi) {
    Py_XDECREF(capi_layth_tmp); }
  }  /*if (capi_layth_tmp == NULL) ... else of layth*/
  /* End of cleaning variable layth */
  } /*CHECKSCALAR(len(alay)>=nbpts)*/
  } /*if (f2py_success) of nbpts*/
  /* End of cleaning variable nbpts */
  if((PyObject *)capi_alay_tmp!=alay_capi) {
    Py_XDECREF(capi_alay_tmp); }
  }  /*if (capi_alay_tmp == NULL) ... else of alay*/
  /* End of cleaning variable alay */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of getactlay ******************************/

/********************************* getactlay2 *********************************/
static char doc_f2py_rout_pdalgo_getactlay2[] = "\
alays = getactlay2(alay,layth,laysd,[nbpts,nblay,nbsed])\n\nWrapper for ``getactlay2``.\
\n\nParameters\n----------\n"
"alay : input float\n"
"layth : input rank-2 array('d') with bounds (nbpts,nblay)\n"
"laysd : input rank-3 array('d') with bounds (nbpts,nblay,nbsed)\n"
"\nOther Parameters\n----------------\n"
"nbpts : input int, optional\n    Default: shape(layth,0)\n"
"nblay : input int, optional\n    Default: shape(layth,1)\n"
"nbsed : input int, optional\n    Default: shape(laysd,2)\n"
"\nReturns\n-------\n"
"alays : rank-2 array('d') with bounds (nbpts,nbsed)";
/* extern void F_FUNC(getactlay2,GETACTLAY2)(double*,double*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_pdalgo_getactlay2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double alay = 0;
  PyObject *alay_capi = Py_None;
  double *layth = NULL;
  npy_intp layth_Dims[2] = {-1, -1};
  const int layth_Rank = 2;
  PyArrayObject *capi_layth_tmp = NULL;
  int capi_layth_intent = 0;
  PyObject *layth_capi = Py_None;
  double *laysd = NULL;
  npy_intp laysd_Dims[3] = {-1, -1, -1};
  const int laysd_Rank = 3;
  PyArrayObject *capi_laysd_tmp = NULL;
  int capi_laysd_intent = 0;
  PyObject *laysd_capi = Py_None;
  double *alays = NULL;
  npy_intp alays_Dims[2] = {-1, -1};
  const int alays_Rank = 2;
  PyArrayObject *capi_alays_tmp = NULL;
  int capi_alays_intent = 0;
  int nbpts = 0;
  PyObject *nbpts_capi = Py_None;
  int nblay = 0;
  PyObject *nblay_capi = Py_None;
  int nbsed = 0;
  PyObject *nbsed_capi = Py_None;
  static char *capi_kwlist[] = {"alay","layth","laysd","nbpts","nblay","nbsed",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOO:pdalgo.getactlay2",\
    capi_kwlist,&alay_capi,&layth_capi,&laysd_capi,&nbpts_capi,&nblay_capi,&nbsed_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable layth */
  ;
  capi_layth_intent |= F2PY_INTENT_IN;
  capi_layth_tmp = array_from_pyobj(NPY_DOUBLE,layth_Dims,layth_Rank,capi_layth_intent,layth_capi);
  if (capi_layth_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 2nd argument `layth' of pdalgo.getactlay2 to C/Fortran array" );
  } else {
    layth = (double *)(PyArray_DATA(capi_layth_tmp));

  /* Processing variable alay */
    f2py_success = double_from_pyobj(&alay,alay_capi,"pdalgo.getactlay2() 1st argument (alay) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nbpts */
  if (nbpts_capi == Py_None) nbpts = shape(layth,0); else
    f2py_success = int_from_pyobj(&nbpts,nbpts_capi,"pdalgo.getactlay2() 1st keyword (nbpts) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(layth,0)==nbpts,"shape(layth,0)==nbpts","1st keyword nbpts","getactlay2:nbpts=%d",nbpts) {
  /* Processing variable nblay */
  if (nblay_capi == Py_None) nblay = shape(layth,1); else
    f2py_success = int_from_pyobj(&nblay,nblay_capi,"pdalgo.getactlay2() 2nd keyword (nblay) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(layth,1)==nblay,"shape(layth,1)==nblay","2nd keyword nblay","getactlay2:nblay=%d",nblay) {
  /* Processing variable laysd */
  laysd_Dims[0]=nbpts,laysd_Dims[1]=nblay;
  capi_laysd_intent |= F2PY_INTENT_IN;
  capi_laysd_tmp = array_from_pyobj(NPY_DOUBLE,laysd_Dims,laysd_Rank,capi_laysd_intent,laysd_capi);
  if (capi_laysd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 3rd argument `laysd' of pdalgo.getactlay2 to C/Fortran array" );
  } else {
    laysd = (double *)(PyArray_DATA(capi_laysd_tmp));

  /* Processing variable nbsed */
  if (nbsed_capi == Py_None) nbsed = shape(laysd,2); else
    f2py_success = int_from_pyobj(&nbsed,nbsed_capi,"pdalgo.getactlay2() 3rd keyword (nbsed) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(laysd,2)==nbsed,"shape(laysd,2)==nbsed","3rd keyword nbsed","getactlay2:nbsed=%d",nbsed) {
  /* Processing variable alays */
  alays_Dims[0]=nbpts,alays_Dims[1]=nbsed;
  capi_alays_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alays_tmp = array_from_pyobj(NPY_DOUBLE,alays_Dims,alays_Rank,capi_alays_intent,Py_None);
  if (capi_alays_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `alays' of pdalgo.getactlay2 to C/Fortran array" );
  } else {
    alays = (double *)(PyArray_DATA(capi_alays_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&alay,layth,laysd,alays,&nbpts,&nblay,&nbsed);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_alays_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_alays_tmp == NULL) ... else of alays*/
  /* End of cleaning variable alays */
  } /*CHECKSCALAR(shape(laysd,2)==nbsed)*/
  } /*if (f2py_success) of nbsed*/
  /* End of cleaning variable nbsed */
  if((PyObject *)capi_laysd_tmp!=laysd_capi) {
    Py_XDECREF(capi_laysd_tmp); }
  }  /*if (capi_laysd_tmp == NULL) ... else of laysd*/
  /* End of cleaning variable laysd */
  } /*CHECKSCALAR(shape(layth,1)==nblay)*/
  } /*if (f2py_success) of nblay*/
  /* End of cleaning variable nblay */
  } /*CHECKSCALAR(shape(layth,0)==nbpts)*/
  } /*if (f2py_success) of nbpts*/
  /* End of cleaning variable nbpts */
  } /*if (f2py_success) of alay*/
  /* End of cleaning variable alay */
  if((PyObject *)capi_layth_tmp!=layth_capi) {
    Py_XDECREF(capi_layth_tmp); }
  }  /*if (capi_layth_tmp == NULL) ... else of layth*/
  /* End of cleaning variable layth */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of getactlay2 *****************************/

/******************************** updatestrati ********************************/
static char doc_f2py_rout_pdalgo_updatestrati[] = "\
newh,news = updatestrati(lays,layh,eros,depo,[nbpts,nblay,nbsed])\n\nWrapper for ``updatestrati``.\
\n\nParameters\n----------\n"
"lays : input rank-3 array('d') with bounds (nbpts,nblay,nbsed)\n"
"layh : input rank-2 array('d') with bounds (nbpts,nblay)\n"
"eros : input rank-2 array('d') with bounds (nbpts,nbsed)\n"
"depo : input rank-2 array('d') with bounds (nbpts,nbsed)\n"
"\nOther Parameters\n----------------\n"
"nbpts : input int, optional\n    Default: shape(lays,0)\n"
"nblay : input int, optional\n    Default: shape(lays,1)\n"
"nbsed : input int, optional\n    Default: shape(lays,2)\n"
"\nReturns\n-------\n"
"newh : rank-2 array('d') with bounds (nbpts,nblay)\n"
"news : rank-3 array('d') with bounds (nbpts,nblay,nbsed)";
/* extern void F_FUNC(updatestrati,UPDATESTRATI)(double*,double*,double*,double*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_pdalgo_updatestrati(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *lays = NULL;
  npy_intp lays_Dims[3] = {-1, -1, -1};
  const int lays_Rank = 3;
  PyArrayObject *capi_lays_tmp = NULL;
  int capi_lays_intent = 0;
  PyObject *lays_capi = Py_None;
  double *layh = NULL;
  npy_intp layh_Dims[2] = {-1, -1};
  const int layh_Rank = 2;
  PyArrayObject *capi_layh_tmp = NULL;
  int capi_layh_intent = 0;
  PyObject *layh_capi = Py_None;
  double *eros = NULL;
  npy_intp eros_Dims[2] = {-1, -1};
  const int eros_Rank = 2;
  PyArrayObject *capi_eros_tmp = NULL;
  int capi_eros_intent = 0;
  PyObject *eros_capi = Py_None;
  double *depo = NULL;
  npy_intp depo_Dims[2] = {-1, -1};
  const int depo_Rank = 2;
  PyArrayObject *capi_depo_tmp = NULL;
  int capi_depo_intent = 0;
  PyObject *depo_capi = Py_None;
  double *newh = NULL;
  npy_intp newh_Dims[2] = {-1, -1};
  const int newh_Rank = 2;
  PyArrayObject *capi_newh_tmp = NULL;
  int capi_newh_intent = 0;
  double *news = NULL;
  npy_intp news_Dims[3] = {-1, -1, -1};
  const int news_Rank = 3;
  PyArrayObject *capi_news_tmp = NULL;
  int capi_news_intent = 0;
  int nbpts = 0;
  PyObject *nbpts_capi = Py_None;
  int nblay = 0;
  PyObject *nblay_capi = Py_None;
  int nbsed = 0;
  PyObject *nbsed_capi = Py_None;
  static char *capi_kwlist[] = {"lays","layh","eros","depo","nbpts","nblay","nbsed",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|OOO:pdalgo.updatestrati",\
    capi_kwlist,&lays_capi,&layh_capi,&eros_capi,&depo_capi,&nbpts_capi,&nblay_capi,&nbsed_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lays */
  ;
  capi_lays_intent |= F2PY_INTENT_IN;
  capi_lays_tmp = array_from_pyobj(NPY_DOUBLE,lays_Dims,lays_Rank,capi_lays_intent,lays_capi);
  if (capi_lays_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 1st argument `lays' of pdalgo.updatestrati to C/Fortran array" );
  } else {
    lays = (double *)(PyArray_DATA(capi_lays_tmp));

  /* Processing variable nbsed */
  if (nbsed_capi == Py_None) nbsed = shape(lays,2); else
    f2py_success = int_from_pyobj(&nbsed,nbsed_capi,"pdalgo.updatestrati() 3rd keyword (nbsed) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,2)==nbsed,"shape(lays,2)==nbsed","3rd keyword nbsed","updatestrati:nbsed=%d",nbsed) {
  /* Processing variable nblay */
  if (nblay_capi == Py_None) nblay = shape(lays,1); else
    f2py_success = int_from_pyobj(&nblay,nblay_capi,"pdalgo.updatestrati() 2nd keyword (nblay) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,1)==nblay,"shape(lays,1)==nblay","2nd keyword nblay","updatestrati:nblay=%d",nblay) {
  /* Processing variable nbpts */
  if (nbpts_capi == Py_None) nbpts = shape(lays,0); else
    f2py_success = int_from_pyobj(&nbpts,nbpts_capi,"pdalgo.updatestrati() 1st keyword (nbpts) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,0)==nbpts,"shape(lays,0)==nbpts","1st keyword nbpts","updatestrati:nbpts=%d",nbpts) {
  /* Processing variable newh */
  newh_Dims[0]=nbpts,newh_Dims[1]=nblay;
  capi_newh_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_newh_tmp = array_from_pyobj(NPY_DOUBLE,newh_Dims,newh_Rank,capi_newh_intent,Py_None);
  if (capi_newh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `newh' of pdalgo.updatestrati to C/Fortran array" );
  } else {
    newh = (double *)(PyArray_DATA(capi_newh_tmp));

  /* Processing variable layh */
  layh_Dims[0]=nbpts,layh_Dims[1]=nblay;
  capi_layh_intent |= F2PY_INTENT_IN;
  capi_layh_tmp = array_from_pyobj(NPY_DOUBLE,layh_Dims,layh_Rank,capi_layh_intent,layh_capi);
  if (capi_layh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 2nd argument `layh' of pdalgo.updatestrati to C/Fortran array" );
  } else {
    layh = (double *)(PyArray_DATA(capi_layh_tmp));

  /* Processing variable depo */
  depo_Dims[0]=nbpts,depo_Dims[1]=nbsed;
  capi_depo_intent |= F2PY_INTENT_IN;
  capi_depo_tmp = array_from_pyobj(NPY_DOUBLE,depo_Dims,depo_Rank,capi_depo_intent,depo_capi);
  if (capi_depo_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 4th argument `depo' of pdalgo.updatestrati to C/Fortran array" );
  } else {
    depo = (double *)(PyArray_DATA(capi_depo_tmp));

  /* Processing variable eros */
  eros_Dims[0]=nbpts,eros_Dims[1]=nbsed;
  capi_eros_intent |= F2PY_INTENT_IN;
  capi_eros_tmp = array_from_pyobj(NPY_DOUBLE,eros_Dims,eros_Rank,capi_eros_intent,eros_capi);
  if (capi_eros_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 3rd argument `eros' of pdalgo.updatestrati to C/Fortran array" );
  } else {
    eros = (double *)(PyArray_DATA(capi_eros_tmp));

  /* Processing variable news */
  news_Dims[0]=nbpts,news_Dims[1]=nblay,news_Dims[2]=nbsed;
  capi_news_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_news_tmp = array_from_pyobj(NPY_DOUBLE,news_Dims,news_Rank,capi_news_intent,Py_None);
  if (capi_news_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `news' of pdalgo.updatestrati to C/Fortran array" );
  } else {
    news = (double *)(PyArray_DATA(capi_news_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(lays,layh,eros,depo,newh,news,&nbpts,&nblay,&nbsed);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_newh_tmp,capi_news_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_news_tmp == NULL) ... else of news*/
  /* End of cleaning variable news */
  if((PyObject *)capi_eros_tmp!=eros_capi) {
    Py_XDECREF(capi_eros_tmp); }
  }  /*if (capi_eros_tmp == NULL) ... else of eros*/
  /* End of cleaning variable eros */
  if((PyObject *)capi_depo_tmp!=depo_capi) {
    Py_XDECREF(capi_depo_tmp); }
  }  /*if (capi_depo_tmp == NULL) ... else of depo*/
  /* End of cleaning variable depo */
  if((PyObject *)capi_layh_tmp!=layh_capi) {
    Py_XDECREF(capi_layh_tmp); }
  }  /*if (capi_layh_tmp == NULL) ... else of layh*/
  /* End of cleaning variable layh */
  }  /*if (capi_newh_tmp == NULL) ... else of newh*/
  /* End of cleaning variable newh */
  } /*CHECKSCALAR(shape(lays,0)==nbpts)*/
  } /*if (f2py_success) of nbpts*/
  /* End of cleaning variable nbpts */
  } /*CHECKSCALAR(shape(lays,1)==nblay)*/
  } /*if (f2py_success) of nblay*/
  /* End of cleaning variable nblay */
  } /*CHECKSCALAR(shape(lays,2)==nbsed)*/
  } /*if (f2py_success) of nbsed*/
  /* End of cleaning variable nbsed */
  if((PyObject *)capi_lays_tmp!=lays_capi) {
    Py_XDECREF(capi_lays_tmp); }
  }  /*if (capi_lays_tmp == NULL) ... else of lays*/
  /* End of cleaning variable lays */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of updatestrati ****************************/

/******************************* updatecstrati *******************************/
static char doc_f2py_rout_pdalgo_updatecstrati[] = "\
newh,news = updatecstrati(lays,layh,eros,depo,[nbpts,nblay,nbsed])\n\nWrapper for ``updatecstrati``.\
\n\nParameters\n----------\n"
"lays : input rank-3 array('d') with bounds (nbpts,nblay,nbsed)\n"
"layh : input rank-2 array('d') with bounds (nbpts,nblay)\n"
"eros : input rank-1 array('d') with bounds (nbpts)\n"
"depo : input rank-1 array('d') with bounds (nbpts)\n"
"\nOther Parameters\n----------------\n"
"nbpts : input int, optional\n    Default: shape(lays,0)\n"
"nblay : input int, optional\n    Default: shape(lays,1)\n"
"nbsed : input int, optional\n    Default: shape(lays,2)\n"
"\nReturns\n-------\n"
"newh : rank-2 array('d') with bounds (nbpts,nblay)\n"
"news : rank-2 array('d') with bounds (nbpts,nblay)";
/* extern void F_FUNC(updatecstrati,UPDATECSTRATI)(double*,double*,double*,double*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_pdalgo_updatecstrati(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *lays = NULL;
  npy_intp lays_Dims[3] = {-1, -1, -1};
  const int lays_Rank = 3;
  PyArrayObject *capi_lays_tmp = NULL;
  int capi_lays_intent = 0;
  PyObject *lays_capi = Py_None;
  double *layh = NULL;
  npy_intp layh_Dims[2] = {-1, -1};
  const int layh_Rank = 2;
  PyArrayObject *capi_layh_tmp = NULL;
  int capi_layh_intent = 0;
  PyObject *layh_capi = Py_None;
  double *eros = NULL;
  npy_intp eros_Dims[1] = {-1};
  const int eros_Rank = 1;
  PyArrayObject *capi_eros_tmp = NULL;
  int capi_eros_intent = 0;
  PyObject *eros_capi = Py_None;
  double *depo = NULL;
  npy_intp depo_Dims[1] = {-1};
  const int depo_Rank = 1;
  PyArrayObject *capi_depo_tmp = NULL;
  int capi_depo_intent = 0;
  PyObject *depo_capi = Py_None;
  double *newh = NULL;
  npy_intp newh_Dims[2] = {-1, -1};
  const int newh_Rank = 2;
  PyArrayObject *capi_newh_tmp = NULL;
  int capi_newh_intent = 0;
  double *news = NULL;
  npy_intp news_Dims[2] = {-1, -1};
  const int news_Rank = 2;
  PyArrayObject *capi_news_tmp = NULL;
  int capi_news_intent = 0;
  int nbpts = 0;
  PyObject *nbpts_capi = Py_None;
  int nblay = 0;
  PyObject *nblay_capi = Py_None;
  int nbsed = 0;
  PyObject *nbsed_capi = Py_None;
  static char *capi_kwlist[] = {"lays","layh","eros","depo","nbpts","nblay","nbsed",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|OOO:pdalgo.updatecstrati",\
    capi_kwlist,&lays_capi,&layh_capi,&eros_capi,&depo_capi,&nbpts_capi,&nblay_capi,&nbsed_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lays */
  ;
  capi_lays_intent |= F2PY_INTENT_IN;
  capi_lays_tmp = array_from_pyobj(NPY_DOUBLE,lays_Dims,lays_Rank,capi_lays_intent,lays_capi);
  if (capi_lays_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 1st argument `lays' of pdalgo.updatecstrati to C/Fortran array" );
  } else {
    lays = (double *)(PyArray_DATA(capi_lays_tmp));

  /* Processing variable nbsed */
  if (nbsed_capi == Py_None) nbsed = shape(lays,2); else
    f2py_success = int_from_pyobj(&nbsed,nbsed_capi,"pdalgo.updatecstrati() 3rd keyword (nbsed) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,2)==nbsed,"shape(lays,2)==nbsed","3rd keyword nbsed","updatecstrati:nbsed=%d",nbsed) {
  /* Processing variable nblay */
  if (nblay_capi == Py_None) nblay = shape(lays,1); else
    f2py_success = int_from_pyobj(&nblay,nblay_capi,"pdalgo.updatecstrati() 2nd keyword (nblay) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,1)==nblay,"shape(lays,1)==nblay","2nd keyword nblay","updatecstrati:nblay=%d",nblay) {
  /* Processing variable nbpts */
  if (nbpts_capi == Py_None) nbpts = shape(lays,0); else
    f2py_success = int_from_pyobj(&nbpts,nbpts_capi,"pdalgo.updatecstrati() 1st keyword (nbpts) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,0)==nbpts,"shape(lays,0)==nbpts","1st keyword nbpts","updatecstrati:nbpts=%d",nbpts) {
  /* Processing variable newh */
  newh_Dims[0]=nbpts,newh_Dims[1]=nblay;
  capi_newh_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_newh_tmp = array_from_pyobj(NPY_DOUBLE,newh_Dims,newh_Rank,capi_newh_intent,Py_None);
  if (capi_newh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `newh' of pdalgo.updatecstrati to C/Fortran array" );
  } else {
    newh = (double *)(PyArray_DATA(capi_newh_tmp));

  /* Processing variable layh */
  layh_Dims[0]=nbpts,layh_Dims[1]=nblay;
  capi_layh_intent |= F2PY_INTENT_IN;
  capi_layh_tmp = array_from_pyobj(NPY_DOUBLE,layh_Dims,layh_Rank,capi_layh_intent,layh_capi);
  if (capi_layh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 2nd argument `layh' of pdalgo.updatecstrati to C/Fortran array" );
  } else {
    layh = (double *)(PyArray_DATA(capi_layh_tmp));

  /* Processing variable depo */
  depo_Dims[0]=nbpts;
  capi_depo_intent |= F2PY_INTENT_IN;
  capi_depo_tmp = array_from_pyobj(NPY_DOUBLE,depo_Dims,depo_Rank,capi_depo_intent,depo_capi);
  if (capi_depo_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 4th argument `depo' of pdalgo.updatecstrati to C/Fortran array" );
  } else {
    depo = (double *)(PyArray_DATA(capi_depo_tmp));

  /* Processing variable eros */
  eros_Dims[0]=nbpts;
  capi_eros_intent |= F2PY_INTENT_IN;
  capi_eros_tmp = array_from_pyobj(NPY_DOUBLE,eros_Dims,eros_Rank,capi_eros_intent,eros_capi);
  if (capi_eros_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 3rd argument `eros' of pdalgo.updatecstrati to C/Fortran array" );
  } else {
    eros = (double *)(PyArray_DATA(capi_eros_tmp));

  /* Processing variable news */
  news_Dims[0]=nbpts,news_Dims[1]=nblay;
  capi_news_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_news_tmp = array_from_pyobj(NPY_DOUBLE,news_Dims,news_Rank,capi_news_intent,Py_None);
  if (capi_news_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `news' of pdalgo.updatecstrati to C/Fortran array" );
  } else {
    news = (double *)(PyArray_DATA(capi_news_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(lays,layh,eros,depo,newh,news,&nbpts,&nblay,&nbsed);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_newh_tmp,capi_news_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_news_tmp == NULL) ... else of news*/
  /* End of cleaning variable news */
  if((PyObject *)capi_eros_tmp!=eros_capi) {
    Py_XDECREF(capi_eros_tmp); }
  }  /*if (capi_eros_tmp == NULL) ... else of eros*/
  /* End of cleaning variable eros */
  if((PyObject *)capi_depo_tmp!=depo_capi) {
    Py_XDECREF(capi_depo_tmp); }
  }  /*if (capi_depo_tmp == NULL) ... else of depo*/
  /* End of cleaning variable depo */
  if((PyObject *)capi_layh_tmp!=layh_capi) {
    Py_XDECREF(capi_layh_tmp); }
  }  /*if (capi_layh_tmp == NULL) ... else of layh*/
  /* End of cleaning variable layh */
  }  /*if (capi_newh_tmp == NULL) ... else of newh*/
  /* End of cleaning variable newh */
  } /*CHECKSCALAR(shape(lays,0)==nbpts)*/
  } /*if (f2py_success) of nbpts*/
  /* End of cleaning variable nbpts */
  } /*CHECKSCALAR(shape(lays,1)==nblay)*/
  } /*if (f2py_success) of nblay*/
  /* End of cleaning variable nblay */
  } /*CHECKSCALAR(shape(lays,2)==nbsed)*/
  } /*if (f2py_success) of nbsed*/
  /* End of cleaning variable nbsed */
  if((PyObject *)capi_lays_tmp!=lays_capi) {
    Py_XDECREF(capi_lays_tmp); }
  }  /*if (capi_lays_tmp == NULL) ... else of lays*/
  /* End of cleaning variable lays */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of updatecstrati ****************************/

/********************************* stratcarb *********************************/
static char doc_f2py_rout_pdalgo_stratcarb[] = "\
newh,news = stratcarb(lays,layh,clastic,[nbpts,nblay,nbsed])\n\nWrapper for ``stratcarb``.\
\n\nParameters\n----------\n"
"lays : input rank-3 array('d') with bounds (nbpts,nblay,nbsed)\n"
"layh : input rank-2 array('d') with bounds (nbpts,nblay)\n"
"clastic : input rank-1 array('d') with bounds (nbpts)\n"
"\nOther Parameters\n----------------\n"
"nbpts : input int, optional\n    Default: shape(lays,0)\n"
"nblay : input int, optional\n    Default: shape(lays,1)\n"
"nbsed : input int, optional\n    Default: shape(lays,2)\n"
"\nReturns\n-------\n"
"newh : rank-2 array('d') with bounds (nbpts,nblay)\n"
"news : rank-3 array('d') with bounds (nbpts,nblay,nbsed)";
/* extern void F_FUNC(stratcarb,STRATCARB)(double*,double*,double*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_pdalgo_stratcarb(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *lays = NULL;
  npy_intp lays_Dims[3] = {-1, -1, -1};
  const int lays_Rank = 3;
  PyArrayObject *capi_lays_tmp = NULL;
  int capi_lays_intent = 0;
  PyObject *lays_capi = Py_None;
  double *layh = NULL;
  npy_intp layh_Dims[2] = {-1, -1};
  const int layh_Rank = 2;
  PyArrayObject *capi_layh_tmp = NULL;
  int capi_layh_intent = 0;
  PyObject *layh_capi = Py_None;
  double *clastic = NULL;
  npy_intp clastic_Dims[1] = {-1};
  const int clastic_Rank = 1;
  PyArrayObject *capi_clastic_tmp = NULL;
  int capi_clastic_intent = 0;
  PyObject *clastic_capi = Py_None;
  double *newh = NULL;
  npy_intp newh_Dims[2] = {-1, -1};
  const int newh_Rank = 2;
  PyArrayObject *capi_newh_tmp = NULL;
  int capi_newh_intent = 0;
  double *news = NULL;
  npy_intp news_Dims[3] = {-1, -1, -1};
  const int news_Rank = 3;
  PyArrayObject *capi_news_tmp = NULL;
  int capi_news_intent = 0;
  int nbpts = 0;
  PyObject *nbpts_capi = Py_None;
  int nblay = 0;
  PyObject *nblay_capi = Py_None;
  int nbsed = 0;
  PyObject *nbsed_capi = Py_None;
  static char *capi_kwlist[] = {"lays","layh","clastic","nbpts","nblay","nbsed",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOO:pdalgo.stratcarb",\
    capi_kwlist,&lays_capi,&layh_capi,&clastic_capi,&nbpts_capi,&nblay_capi,&nbsed_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lays */
  ;
  capi_lays_intent |= F2PY_INTENT_IN;
  capi_lays_tmp = array_from_pyobj(NPY_DOUBLE,lays_Dims,lays_Rank,capi_lays_intent,lays_capi);
  if (capi_lays_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 1st argument `lays' of pdalgo.stratcarb to C/Fortran array" );
  } else {
    lays = (double *)(PyArray_DATA(capi_lays_tmp));

  /* Processing variable nbsed */
  if (nbsed_capi == Py_None) nbsed = shape(lays,2); else
    f2py_success = int_from_pyobj(&nbsed,nbsed_capi,"pdalgo.stratcarb() 3rd keyword (nbsed) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,2)==nbsed,"shape(lays,2)==nbsed","3rd keyword nbsed","stratcarb:nbsed=%d",nbsed) {
  /* Processing variable nblay */
  if (nblay_capi == Py_None) nblay = shape(lays,1); else
    f2py_success = int_from_pyobj(&nblay,nblay_capi,"pdalgo.stratcarb() 2nd keyword (nblay) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,1)==nblay,"shape(lays,1)==nblay","2nd keyword nblay","stratcarb:nblay=%d",nblay) {
  /* Processing variable nbpts */
  if (nbpts_capi == Py_None) nbpts = shape(lays,0); else
    f2py_success = int_from_pyobj(&nbpts,nbpts_capi,"pdalgo.stratcarb() 1st keyword (nbpts) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(lays,0)==nbpts,"shape(lays,0)==nbpts","1st keyword nbpts","stratcarb:nbpts=%d",nbpts) {
  /* Processing variable newh */
  newh_Dims[0]=nbpts,newh_Dims[1]=nblay;
  capi_newh_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_newh_tmp = array_from_pyobj(NPY_DOUBLE,newh_Dims,newh_Rank,capi_newh_intent,Py_None);
  if (capi_newh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `newh' of pdalgo.stratcarb to C/Fortran array" );
  } else {
    newh = (double *)(PyArray_DATA(capi_newh_tmp));

  /* Processing variable layh */
  layh_Dims[0]=nbpts,layh_Dims[1]=nblay;
  capi_layh_intent |= F2PY_INTENT_IN;
  capi_layh_tmp = array_from_pyobj(NPY_DOUBLE,layh_Dims,layh_Rank,capi_layh_intent,layh_capi);
  if (capi_layh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 2nd argument `layh' of pdalgo.stratcarb to C/Fortran array" );
  } else {
    layh = (double *)(PyArray_DATA(capi_layh_tmp));

  /* Processing variable clastic */
  clastic_Dims[0]=nbpts;
  capi_clastic_intent |= F2PY_INTENT_IN;
  capi_clastic_tmp = array_from_pyobj(NPY_DOUBLE,clastic_Dims,clastic_Rank,capi_clastic_intent,clastic_capi);
  if (capi_clastic_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting 3rd argument `clastic' of pdalgo.stratcarb to C/Fortran array" );
  } else {
    clastic = (double *)(PyArray_DATA(capi_clastic_tmp));

  /* Processing variable news */
  news_Dims[0]=nbpts,news_Dims[1]=nblay,news_Dims[2]=nbsed;
  capi_news_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_news_tmp = array_from_pyobj(NPY_DOUBLE,news_Dims,news_Rank,capi_news_intent,Py_None);
  if (capi_news_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(pdalgo_error,"failed in converting hidden `news' of pdalgo.stratcarb to C/Fortran array" );
  } else {
    news = (double *)(PyArray_DATA(capi_news_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(lays,layh,clastic,newh,news,&nbpts,&nblay,&nbsed);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_newh_tmp,capi_news_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_news_tmp == NULL) ... else of news*/
  /* End of cleaning variable news */
  if((PyObject *)capi_clastic_tmp!=clastic_capi) {
    Py_XDECREF(capi_clastic_tmp); }
  }  /*if (capi_clastic_tmp == NULL) ... else of clastic*/
  /* End of cleaning variable clastic */
  if((PyObject *)capi_layh_tmp!=layh_capi) {
    Py_XDECREF(capi_layh_tmp); }
  }  /*if (capi_layh_tmp == NULL) ... else of layh*/
  /* End of cleaning variable layh */
  }  /*if (capi_newh_tmp == NULL) ... else of newh*/
  /* End of cleaning variable newh */
  } /*CHECKSCALAR(shape(lays,0)==nbpts)*/
  } /*if (f2py_success) of nbpts*/
  /* End of cleaning variable nbpts */
  } /*CHECKSCALAR(shape(lays,1)==nblay)*/
  } /*if (f2py_success) of nblay*/
  /* End of cleaning variable nblay */
  } /*CHECKSCALAR(shape(lays,2)==nbsed)*/
  } /*if (f2py_success) of nbsed*/
  /* End of cleaning variable nbsed */
  if((PyObject *)capi_lays_tmp!=lays_capi) {
    Py_XDECREF(capi_lays_tmp); }
  }  /*if (capi_lays_tmp == NULL) ... else of lays*/
  /* End of cleaning variable lays */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of stratcarb ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"marine_distribution",-1,{{-1}},0,(char *)F_FUNC_US(marine_distribution,MARINE_DISTRIBUTION),(f2py_init_func)f2py_rout_pdalgo_marine_distribution,doc_f2py_rout_pdalgo_marine_distribution},
  {"pitparams",-1,{{-1}},0,(char *)F_FUNC(pitparams,PITPARAMS),(f2py_init_func)f2py_rout_pdalgo_pitparams,doc_f2py_rout_pdalgo_pitparams},
  {"pitfilling",-1,{{-1}},0,(char *)F_FUNC(pitfilling,PITFILLING),(f2py_init_func)f2py_rout_pdalgo_pitfilling,doc_f2py_rout_pdalgo_pitfilling},
  {"getactlay",-1,{{-1}},0,(char *)F_FUNC(getactlay,GETACTLAY),(f2py_init_func)f2py_rout_pdalgo_getactlay,doc_f2py_rout_pdalgo_getactlay},
  {"getactlay2",-1,{{-1}},0,(char *)F_FUNC(getactlay2,GETACTLAY2),(f2py_init_func)f2py_rout_pdalgo_getactlay2,doc_f2py_rout_pdalgo_getactlay2},
  {"updatestrati",-1,{{-1}},0,(char *)F_FUNC(updatestrati,UPDATESTRATI),(f2py_init_func)f2py_rout_pdalgo_updatestrati,doc_f2py_rout_pdalgo_updatestrati},
  {"updatecstrati",-1,{{-1}},0,(char *)F_FUNC(updatecstrati,UPDATECSTRATI),(f2py_init_func)f2py_rout_pdalgo_updatecstrati,doc_f2py_rout_pdalgo_updatecstrati},
  {"stratcarb",-1,{{-1}},0,(char *)F_FUNC(stratcarb,STRATCARB),(f2py_init_func)f2py_rout_pdalgo_stratcarb,doc_f2py_rout_pdalgo_stratcarb},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "pdalgo",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_pdalgo(void) {
#else
#define RETVAL
PyMODINIT_FUNC initpdalgo(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = pdalgo_module = PyModule_Create(&moduledef);
#else
  m = pdalgo_module = Py_InitModule("pdalgo", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module pdalgo (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'pdalgo' is auto-generated with f2py (version:2).\nFunctions:\n"
"  diffsed = marine_distribution(elevation,seavol,sealevel,border,depids,pydnodes=len(elevation),pyids=len(depids),pyrocknb=shape(seavol,1))\n"
"  pitparams(pyngbs,pyarea,pydiff,pyprop,fillth,epsilon,pybounds,pydnodes=shape(pyngbs,0))\n"
"  demh = pitfilling(elevation,allfill,sealevel,pydnodes=len(elevation))\n"
"  alays = getactlay(alay,layth,laysd,nbpts=len(alay),nblay=shape(layth,1),nbsed=shape(laysd,2))\n"
"  alays = getactlay2(alay,layth,laysd,nbpts=shape(layth,0),nblay=shape(layth,1),nbsed=shape(laysd,2))\n"
"  newh,news = updatestrati(lays,layh,eros,depo,nbpts=shape(lays,0),nblay=shape(lays,1),nbsed=shape(lays,2))\n"
"  newh,news = updatecstrati(lays,layh,eros,depo,nbpts=shape(lays,0),nblay=shape(lays,1),nbsed=shape(lays,2))\n"
"  newh,news = stratcarb(lays,layh,clastic,nbpts=shape(lays,0),nblay=shape(lays,1),nbsed=shape(lays,2))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  pdalgo_error = PyErr_NewException ("pdalgo.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"pdalgo");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
