/* File: sfdmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Aug 14 11:59:45 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *sfd_error;
static PyObject *sfd_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = sfd_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = sfd_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void dirview(double*,double*,int*,double*,double*,int*,double,int*,int*,int,int);
extern void directions(double*,double*,int*,double*,double*,int*,int*,int*,double*,double*,int,int);
extern void directions_base(double*,int*,double*,double*,int*,int*,int*,int,int);
extern void diffusion(double*,int*,int*,double*,double*,int*,double*,int,int);
extern void diffnlcfl(double*,double*,double*,int*,int*,double*,int*,double*,int,int);
extern void diffusionnl(double*,double*,int*,int*,double*,double*,int*,double*,int,int);
extern void diffusionero(double*,int*,int*,double*,double*,int*,double*,int,int);
extern void diffusionmarine(double*,int*,int*,int*,double*,double*,int*,double*,int,int);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** dirview **********************************/
static char doc_f2py_rout_sfd_dirview[] = "\
pyBase,pyRcv = dirview(pyElev,pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,sealimit,[pylocalNb,pyglobalNb])\n\nWrapper for ``dirview``.\
\n\nParameters\n----------\n"
"pyElev : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyEdge : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"sealimit : input float\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyBase : rank-1 array('i') with bounds (pyglobalNb)\n"
"pyRcv : rank-1 array('i') with bounds (pyglobalNb)";
/* extern void dirview(double*,double*,int*,double*,double*,int*,double,int*,int*,int,int); */
static PyObject *f2py_rout_sfd_dirview(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,double*,int*,double,int*,int*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pyElev = NULL;
  npy_intp pyElev_Dims[1] = {-1};
  const int pyElev_Rank = 1;
  PyArrayObject *capi_pyElev_tmp = NULL;
  int capi_pyElev_intent = 0;
  PyObject *pyElev_capi = Py_None;
  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyEdge = NULL;
  npy_intp pyEdge_Dims[2] = {-1, -1};
  const int pyEdge_Rank = 2;
  PyArrayObject *capi_pyEdge_tmp = NULL;
  int capi_pyEdge_intent = 0;
  PyObject *pyEdge_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  double sealimit = 0;
  PyObject *sealimit_capi = Py_None;
  int *pyBase = NULL;
  npy_intp pyBase_Dims[1] = {-1};
  const int pyBase_Rank = 1;
  PyArrayObject *capi_pyBase_tmp = NULL;
  int capi_pyBase_intent = 0;
  int *pyRcv = NULL;
  npy_intp pyRcv_Dims[1] = {-1};
  const int pyRcv_Rank = 1;
  PyArrayObject *capi_pyRcv_tmp = NULL;
  int capi_pyRcv_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pyElev","pyZ","pyNgbs","pyEdge","pyDist","pyGIDs","sealimit","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|OO:sfd.dirview",\
    capi_kwlist,&pyElev_capi,&pyZ_capi,&pyNgbs_capi,&pyEdge_capi,&pyDist_capi,&pyGIDs_capi,&sealimit_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 6th argument `pyGIDs' of sfd.dirview to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable sealimit */
    f2py_success = double_from_pyobj(&sealimit,sealimit_capi,"sfd.dirview() 7th argument (sealimit) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyNgbs' of sfd.dirview to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.dirview() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.dirview() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyZ' of sfd.dirview to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

  /* Processing variable pyElev */
  pyElev_Dims[0]=pyglobalNb;
  capi_pyElev_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyElev_tmp = array_from_pyobj(NPY_DOUBLE,pyElev_Dims,pyElev_Rank,capi_pyElev_intent,pyElev_capi);
  if (capi_pyElev_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pyElev' of sfd.dirview to C/Fortran array" );
  } else {
    pyElev = (double *)(PyArray_DATA(capi_pyElev_tmp));

  /* Processing variable pyRcv */
  pyRcv_Dims[0]=pyglobalNb;
  capi_pyRcv_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyRcv_tmp = array_from_pyobj(NPY_INT,pyRcv_Dims,pyRcv_Rank,capi_pyRcv_intent,Py_None);
  if (capi_pyRcv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyRcv' of sfd.dirview to C/Fortran array" );
  } else {
    pyRcv = (int *)(PyArray_DATA(capi_pyRcv_tmp));

  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyDist' of sfd.dirview to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyEdge */
  pyEdge_Dims[0]=pyglobalNb,pyEdge_Dims[1]=20;
  capi_pyEdge_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyEdge_tmp = array_from_pyobj(NPY_DOUBLE,pyEdge_Dims,pyEdge_Rank,capi_pyEdge_intent,pyEdge_capi);
  if (capi_pyEdge_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyEdge' of sfd.dirview to C/Fortran array" );
  } else {
    pyEdge = (double *)(PyArray_DATA(capi_pyEdge_tmp));

  /* Processing variable pyBase */
  pyBase_Dims[0]=pyglobalNb;
  capi_pyBase_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyBase_tmp = array_from_pyobj(NPY_INT,pyBase_Dims,pyBase_Rank,capi_pyBase_intent,Py_None);
  if (capi_pyBase_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyBase' of sfd.dirview to C/Fortran array" );
  } else {
    pyBase = (int *)(PyArray_DATA(capi_pyBase_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyElev,pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,sealimit,pyBase,pyRcv,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_pyBase_tmp,capi_pyRcv_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_pyBase_tmp == NULL) ... else of pyBase*/
  /* End of cleaning variable pyBase */
  if((PyObject *)capi_pyEdge_tmp!=pyEdge_capi) {
    Py_XDECREF(capi_pyEdge_tmp); }
  }  /*if (capi_pyEdge_tmp == NULL) ... else of pyEdge*/
  /* End of cleaning variable pyEdge */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  }  /*if (capi_pyRcv_tmp == NULL) ... else of pyRcv*/
  /* End of cleaning variable pyRcv */
  if((PyObject *)capi_pyElev_tmp!=pyElev_capi) {
    Py_XDECREF(capi_pyElev_tmp); }
  }  /*if (capi_pyElev_tmp == NULL) ... else of pyElev*/
  /* End of cleaning variable pyElev */
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  } /*if (f2py_success) of sealimit*/
  /* End of cleaning variable sealimit */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of dirview *******************************/

/********************************* directions *********************************/
static char doc_f2py_rout_sfd_directions[] = "\
pyBase,pyRcv,pyMaxh,pyMaxDep = directions(pyElev,pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,[pylocalNb,pyglobalNb])\n\nWrapper for ``directions``.\
\n\nParameters\n----------\n"
"pyElev : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyEdge : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyBase : rank-1 array('i') with bounds (pyglobalNb)\n"
"pyRcv : rank-1 array('i') with bounds (pyglobalNb)\n"
"pyMaxh : rank-1 array('d') with bounds (pyglobalNb)\n"
"pyMaxDep : rank-1 array('d') with bounds (pyglobalNb)";
/* extern void directions(double*,double*,int*,double*,double*,int*,int*,int*,double*,double*,int,int); */
static PyObject *f2py_rout_sfd_directions(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,double*,int*,int*,int*,double*,double*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pyElev = NULL;
  npy_intp pyElev_Dims[1] = {-1};
  const int pyElev_Rank = 1;
  PyArrayObject *capi_pyElev_tmp = NULL;
  int capi_pyElev_intent = 0;
  PyObject *pyElev_capi = Py_None;
  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyEdge = NULL;
  npy_intp pyEdge_Dims[2] = {-1, -1};
  const int pyEdge_Rank = 2;
  PyArrayObject *capi_pyEdge_tmp = NULL;
  int capi_pyEdge_intent = 0;
  PyObject *pyEdge_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  int *pyBase = NULL;
  npy_intp pyBase_Dims[1] = {-1};
  const int pyBase_Rank = 1;
  PyArrayObject *capi_pyBase_tmp = NULL;
  int capi_pyBase_intent = 0;
  int *pyRcv = NULL;
  npy_intp pyRcv_Dims[1] = {-1};
  const int pyRcv_Rank = 1;
  PyArrayObject *capi_pyRcv_tmp = NULL;
  int capi_pyRcv_intent = 0;
  double *pyMaxh = NULL;
  npy_intp pyMaxh_Dims[1] = {-1};
  const int pyMaxh_Rank = 1;
  PyArrayObject *capi_pyMaxh_tmp = NULL;
  int capi_pyMaxh_intent = 0;
  double *pyMaxDep = NULL;
  npy_intp pyMaxDep_Dims[1] = {-1};
  const int pyMaxDep_Rank = 1;
  PyArrayObject *capi_pyMaxDep_tmp = NULL;
  int capi_pyMaxDep_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pyElev","pyZ","pyNgbs","pyEdge","pyDist","pyGIDs","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OO:sfd.directions",\
    capi_kwlist,&pyElev_capi,&pyZ_capi,&pyNgbs_capi,&pyEdge_capi,&pyDist_capi,&pyGIDs_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 6th argument `pyGIDs' of sfd.directions to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyNgbs' of sfd.directions to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.directions() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyDist' of sfd.directions to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyZ' of sfd.directions to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

  /* Processing variable pyMaxh */
  pyMaxh_Dims[0]=pyglobalNb;
  capi_pyMaxh_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyMaxh_tmp = array_from_pyobj(NPY_DOUBLE,pyMaxh_Dims,pyMaxh_Rank,capi_pyMaxh_intent,Py_None);
  if (capi_pyMaxh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyMaxh' of sfd.directions to C/Fortran array" );
  } else {
    pyMaxh = (double *)(PyArray_DATA(capi_pyMaxh_tmp));

  /* Processing variable pyElev */
  pyElev_Dims[0]=pyglobalNb;
  capi_pyElev_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyElev_tmp = array_from_pyobj(NPY_DOUBLE,pyElev_Dims,pyElev_Rank,capi_pyElev_intent,pyElev_capi);
  if (capi_pyElev_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pyElev' of sfd.directions to C/Fortran array" );
  } else {
    pyElev = (double *)(PyArray_DATA(capi_pyElev_tmp));

  /* Processing variable pyMaxDep */
  pyMaxDep_Dims[0]=pyglobalNb;
  capi_pyMaxDep_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyMaxDep_tmp = array_from_pyobj(NPY_DOUBLE,pyMaxDep_Dims,pyMaxDep_Rank,capi_pyMaxDep_intent,Py_None);
  if (capi_pyMaxDep_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyMaxDep' of sfd.directions to C/Fortran array" );
  } else {
    pyMaxDep = (double *)(PyArray_DATA(capi_pyMaxDep_tmp));

  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.directions() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyRcv */
  pyRcv_Dims[0]=pyglobalNb;
  capi_pyRcv_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyRcv_tmp = array_from_pyobj(NPY_INT,pyRcv_Dims,pyRcv_Rank,capi_pyRcv_intent,Py_None);
  if (capi_pyRcv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyRcv' of sfd.directions to C/Fortran array" );
  } else {
    pyRcv = (int *)(PyArray_DATA(capi_pyRcv_tmp));

  /* Processing variable pyEdge */
  pyEdge_Dims[0]=pyglobalNb,pyEdge_Dims[1]=20;
  capi_pyEdge_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyEdge_tmp = array_from_pyobj(NPY_DOUBLE,pyEdge_Dims,pyEdge_Rank,capi_pyEdge_intent,pyEdge_capi);
  if (capi_pyEdge_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyEdge' of sfd.directions to C/Fortran array" );
  } else {
    pyEdge = (double *)(PyArray_DATA(capi_pyEdge_tmp));

  /* Processing variable pyBase */
  pyBase_Dims[0]=pyglobalNb;
  capi_pyBase_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyBase_tmp = array_from_pyobj(NPY_INT,pyBase_Dims,pyBase_Rank,capi_pyBase_intent,Py_None);
  if (capi_pyBase_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyBase' of sfd.directions to C/Fortran array" );
  } else {
    pyBase = (int *)(PyArray_DATA(capi_pyBase_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyElev,pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,pyBase,pyRcv,pyMaxh,pyMaxDep,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNN",capi_pyBase_tmp,capi_pyRcv_tmp,capi_pyMaxh_tmp,capi_pyMaxDep_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_pyBase_tmp == NULL) ... else of pyBase*/
  /* End of cleaning variable pyBase */
  if((PyObject *)capi_pyEdge_tmp!=pyEdge_capi) {
    Py_XDECREF(capi_pyEdge_tmp); }
  }  /*if (capi_pyEdge_tmp == NULL) ... else of pyEdge*/
  /* End of cleaning variable pyEdge */
  }  /*if (capi_pyRcv_tmp == NULL) ... else of pyRcv*/
  /* End of cleaning variable pyRcv */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  }  /*if (capi_pyMaxDep_tmp == NULL) ... else of pyMaxDep*/
  /* End of cleaning variable pyMaxDep */
  if((PyObject *)capi_pyElev_tmp!=pyElev_capi) {
    Py_XDECREF(capi_pyElev_tmp); }
  }  /*if (capi_pyElev_tmp == NULL) ... else of pyElev*/
  /* End of cleaning variable pyElev */
  }  /*if (capi_pyMaxh_tmp == NULL) ... else of pyMaxh*/
  /* End of cleaning variable pyMaxh */
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of directions *****************************/

/****************************** directions_base ******************************/
static char doc_f2py_rout_sfd_directions_base[] = "\
pyBase,pyRcv = directions_base(pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,[pylocalNb,pyglobalNb])\n\nWrapper for ``directions_base``.\
\n\nParameters\n----------\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyEdge : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyBase : rank-1 array('i') with bounds (pyglobalNb)\n"
"pyRcv : rank-1 array('i') with bounds (pyglobalNb)";
/* extern void directions_base(double*,int*,double*,double*,int*,int*,int*,int,int); */
static PyObject *f2py_rout_sfd_directions_base(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,double*,int*,int*,int*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyEdge = NULL;
  npy_intp pyEdge_Dims[2] = {-1, -1};
  const int pyEdge_Rank = 2;
  PyArrayObject *capi_pyEdge_tmp = NULL;
  int capi_pyEdge_intent = 0;
  PyObject *pyEdge_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  int *pyBase = NULL;
  npy_intp pyBase_Dims[1] = {-1};
  const int pyBase_Rank = 1;
  PyArrayObject *capi_pyBase_tmp = NULL;
  int capi_pyBase_intent = 0;
  int *pyRcv = NULL;
  npy_intp pyRcv_Dims[1] = {-1};
  const int pyRcv_Rank = 1;
  PyArrayObject *capi_pyRcv_tmp = NULL;
  int capi_pyRcv_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pyZ","pyNgbs","pyEdge","pyDist","pyGIDs","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OO:sfd.directions_base",\
    capi_kwlist,&pyZ_capi,&pyNgbs_capi,&pyEdge_capi,&pyDist_capi,&pyGIDs_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyGIDs' of sfd.directions_base to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyNgbs' of sfd.directions_base to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.directions_base() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.directions_base() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pyZ' of sfd.directions_base to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

  /* Processing variable pyRcv */
  pyRcv_Dims[0]=pyglobalNb;
  capi_pyRcv_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyRcv_tmp = array_from_pyobj(NPY_INT,pyRcv_Dims,pyRcv_Rank,capi_pyRcv_intent,Py_None);
  if (capi_pyRcv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyRcv' of sfd.directions_base to C/Fortran array" );
  } else {
    pyRcv = (int *)(PyArray_DATA(capi_pyRcv_tmp));

  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyDist' of sfd.directions_base to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyEdge */
  pyEdge_Dims[0]=pyglobalNb,pyEdge_Dims[1]=20;
  capi_pyEdge_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyEdge_tmp = array_from_pyobj(NPY_DOUBLE,pyEdge_Dims,pyEdge_Rank,capi_pyEdge_intent,pyEdge_capi);
  if (capi_pyEdge_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyEdge' of sfd.directions_base to C/Fortran array" );
  } else {
    pyEdge = (double *)(PyArray_DATA(capi_pyEdge_tmp));

  /* Processing variable pyBase */
  pyBase_Dims[0]=pyglobalNb;
  capi_pyBase_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyBase_tmp = array_from_pyobj(NPY_INT,pyBase_Dims,pyBase_Rank,capi_pyBase_intent,Py_None);
  if (capi_pyBase_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyBase' of sfd.directions_base to C/Fortran array" );
  } else {
    pyBase = (int *)(PyArray_DATA(capi_pyBase_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,pyBase,pyRcv,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_pyBase_tmp,capi_pyRcv_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_pyBase_tmp == NULL) ... else of pyBase*/
  /* End of cleaning variable pyBase */
  if((PyObject *)capi_pyEdge_tmp!=pyEdge_capi) {
    Py_XDECREF(capi_pyEdge_tmp); }
  }  /*if (capi_pyEdge_tmp == NULL) ... else of pyEdge*/
  /* End of cleaning variable pyEdge */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  }  /*if (capi_pyRcv_tmp == NULL) ... else of pyRcv*/
  /* End of cleaning variable pyRcv */
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of directions_base ***************************/

/********************************* diffusion *********************************/
static char doc_f2py_rout_sfd_diffusion[] = "\
pyDiff = diffusion(pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,[pylocalNb,pyglobalNb])\n\nWrapper for ``diffusion``.\
\n\nParameters\n----------\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyBord : input rank-1 array('i') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyEdge : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyDiff : rank-1 array('d') with bounds (pyglobalNb)";
/* extern void diffusion(double*,int*,int*,double*,double*,int*,double*,int,int); */
static PyObject *f2py_rout_sfd_diffusion(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,double*,int*,double*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyBord = NULL;
  npy_intp pyBord_Dims[1] = {-1};
  const int pyBord_Rank = 1;
  PyArrayObject *capi_pyBord_tmp = NULL;
  int capi_pyBord_intent = 0;
  PyObject *pyBord_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyEdge = NULL;
  npy_intp pyEdge_Dims[2] = {-1, -1};
  const int pyEdge_Rank = 2;
  PyArrayObject *capi_pyEdge_tmp = NULL;
  int capi_pyEdge_intent = 0;
  PyObject *pyEdge_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  double *pyDiff = NULL;
  npy_intp pyDiff_Dims[1] = {-1};
  const int pyDiff_Rank = 1;
  PyArrayObject *capi_pyDiff_tmp = NULL;
  int capi_pyDiff_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pyZ","pyBord","pyNgbs","pyEdge","pyDist","pyGIDs","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OO:sfd.diffusion",\
    capi_kwlist,&pyZ_capi,&pyBord_capi,&pyNgbs_capi,&pyEdge_capi,&pyDist_capi,&pyGIDs_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 6th argument `pyGIDs' of sfd.diffusion to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyNgbs' of sfd.diffusion to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.diffusion() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.diffusion() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pyZ' of sfd.diffusion to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

  /* Processing variable pyDiff */
  pyDiff_Dims[0]=pyglobalNb;
  capi_pyDiff_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyDiff_tmp = array_from_pyobj(NPY_DOUBLE,pyDiff_Dims,pyDiff_Rank,capi_pyDiff_intent,Py_None);
  if (capi_pyDiff_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyDiff' of sfd.diffusion to C/Fortran array" );
  } else {
    pyDiff = (double *)(PyArray_DATA(capi_pyDiff_tmp));

  /* Processing variable pyBord */
  pyBord_Dims[0]=pyglobalNb;
  capi_pyBord_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyBord_tmp = array_from_pyobj(NPY_INT,pyBord_Dims,pyBord_Rank,capi_pyBord_intent,pyBord_capi);
  if (capi_pyBord_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyBord' of sfd.diffusion to C/Fortran array" );
  } else {
    pyBord = (int *)(PyArray_DATA(capi_pyBord_tmp));

  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyDist' of sfd.diffusion to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyEdge */
  pyEdge_Dims[0]=pyglobalNb,pyEdge_Dims[1]=20;
  capi_pyEdge_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyEdge_tmp = array_from_pyobj(NPY_DOUBLE,pyEdge_Dims,pyEdge_Rank,capi_pyEdge_intent,pyEdge_capi);
  if (capi_pyEdge_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyEdge' of sfd.diffusion to C/Fortran array" );
  } else {
    pyEdge = (double *)(PyArray_DATA(capi_pyEdge_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,pyDiff,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_pyDiff_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_pyEdge_tmp!=pyEdge_capi) {
    Py_XDECREF(capi_pyEdge_tmp); }
  }  /*if (capi_pyEdge_tmp == NULL) ... else of pyEdge*/
  /* End of cleaning variable pyEdge */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  if((PyObject *)capi_pyBord_tmp!=pyBord_capi) {
    Py_XDECREF(capi_pyBord_tmp); }
  }  /*if (capi_pyBord_tmp == NULL) ... else of pyBord*/
  /* End of cleaning variable pyBord */
  }  /*if (capi_pyDiff_tmp == NULL) ... else of pyDiff*/
  /* End of cleaning variable pyDiff */
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of diffusion ******************************/

/********************************* diffnlcfl *********************************/
static char doc_f2py_rout_sfd_diffnlcfl[] = "\
pyCFL = diffnlcfl(pySc,pyKd,pyZ,pyBord,pyNgbs,pyDist,pyGIDs,[pylocalNb,pyglobalNb])\n\nWrapper for ``diffnlcfl``.\
\n\nParameters\n----------\n"
"pySc : input rank-1 array('d') with bounds (1)\n"
"pyKd : input rank-1 array('d') with bounds (1)\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyBord : input rank-1 array('i') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyCFL : rank-1 array('d') with bounds (1)";
/* extern void diffnlcfl(double*,double*,double*,int*,int*,double*,int*,double*,int,int); */
static PyObject *f2py_rout_sfd_diffnlcfl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*,double*,int*,double*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pySc = NULL;
  npy_intp pySc_Dims[1] = {-1};
  const int pySc_Rank = 1;
  PyArrayObject *capi_pySc_tmp = NULL;
  int capi_pySc_intent = 0;
  PyObject *pySc_capi = Py_None;
  double *pyKd = NULL;
  npy_intp pyKd_Dims[1] = {-1};
  const int pyKd_Rank = 1;
  PyArrayObject *capi_pyKd_tmp = NULL;
  int capi_pyKd_intent = 0;
  PyObject *pyKd_capi = Py_None;
  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyBord = NULL;
  npy_intp pyBord_Dims[1] = {-1};
  const int pyBord_Rank = 1;
  PyArrayObject *capi_pyBord_tmp = NULL;
  int capi_pyBord_intent = 0;
  PyObject *pyBord_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  double *pyCFL = NULL;
  npy_intp pyCFL_Dims[1] = {-1};
  const int pyCFL_Rank = 1;
  PyArrayObject *capi_pyCFL_tmp = NULL;
  int capi_pyCFL_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pySc","pyKd","pyZ","pyBord","pyNgbs","pyDist","pyGIDs","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|OO:sfd.diffnlcfl",\
    capi_kwlist,&pySc_capi,&pyKd_capi,&pyZ_capi,&pyBord_capi,&pyNgbs_capi,&pyDist_capi,&pyGIDs_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pySc */
  pySc_Dims[0]=1;
  capi_pySc_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pySc_tmp = array_from_pyobj(NPY_DOUBLE,pySc_Dims,pySc_Rank,capi_pySc_intent,pySc_capi);
  if (capi_pySc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pySc' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pySc = (double *)(PyArray_DATA(capi_pySc_tmp));

  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 7th argument `pyGIDs' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable pyCFL */
  pyCFL_Dims[0]=1;
  capi_pyCFL_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyCFL_tmp = array_from_pyobj(NPY_DOUBLE,pyCFL_Dims,pyCFL_Rank,capi_pyCFL_intent,Py_None);
  if (capi_pyCFL_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyCFL' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pyCFL = (double *)(PyArray_DATA(capi_pyCFL_tmp));

  /* Processing variable pyKd */
  pyKd_Dims[0]=1;
  capi_pyKd_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyKd_tmp = array_from_pyobj(NPY_DOUBLE,pyKd_Dims,pyKd_Rank,capi_pyKd_intent,pyKd_capi);
  if (capi_pyKd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyKd' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pyKd = (double *)(PyArray_DATA(capi_pyKd_tmp));

  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyNgbs' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.diffnlcfl() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.diffnlcfl() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyBord */
  pyBord_Dims[0]=pyglobalNb;
  capi_pyBord_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyBord_tmp = array_from_pyobj(NPY_INT,pyBord_Dims,pyBord_Rank,capi_pyBord_intent,pyBord_capi);
  if (capi_pyBord_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyBord' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pyBord = (int *)(PyArray_DATA(capi_pyBord_tmp));

  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 6th argument `pyDist' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyZ' of sfd.diffnlcfl to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pySc,pyKd,pyZ,pyBord,pyNgbs,pyDist,pyGIDs,pyCFL,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_pyCFL_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  if((PyObject *)capi_pyBord_tmp!=pyBord_capi) {
    Py_XDECREF(capi_pyBord_tmp); }
  }  /*if (capi_pyBord_tmp == NULL) ... else of pyBord*/
  /* End of cleaning variable pyBord */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  if((PyObject *)capi_pyKd_tmp!=pyKd_capi) {
    Py_XDECREF(capi_pyKd_tmp); }
  }  /*if (capi_pyKd_tmp == NULL) ... else of pyKd*/
  /* End of cleaning variable pyKd */
  }  /*if (capi_pyCFL_tmp == NULL) ... else of pyCFL*/
  /* End of cleaning variable pyCFL */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
  if((PyObject *)capi_pySc_tmp!=pySc_capi) {
    Py_XDECREF(capi_pySc_tmp); }
  }  /*if (capi_pySc_tmp == NULL) ... else of pySc*/
  /* End of cleaning variable pySc */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of diffnlcfl ******************************/

/******************************** diffusionnl ********************************/
static char doc_f2py_rout_sfd_diffusionnl[] = "\
pyDiff = diffusionnl(pySc,pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,[pylocalNb,pyglobalNb])\n\nWrapper for ``diffusionnl``.\
\n\nParameters\n----------\n"
"pySc : input rank-1 array('d') with bounds (1)\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyBord : input rank-1 array('i') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyEdge : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyDiff : rank-1 array('d') with bounds (pyglobalNb)";
/* extern void diffusionnl(double*,double*,int*,int*,double*,double*,int*,double*,int,int); */
static PyObject *f2py_rout_sfd_diffusionnl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,double*,double*,int*,double*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pySc = NULL;
  npy_intp pySc_Dims[1] = {-1};
  const int pySc_Rank = 1;
  PyArrayObject *capi_pySc_tmp = NULL;
  int capi_pySc_intent = 0;
  PyObject *pySc_capi = Py_None;
  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyBord = NULL;
  npy_intp pyBord_Dims[1] = {-1};
  const int pyBord_Rank = 1;
  PyArrayObject *capi_pyBord_tmp = NULL;
  int capi_pyBord_intent = 0;
  PyObject *pyBord_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyEdge = NULL;
  npy_intp pyEdge_Dims[2] = {-1, -1};
  const int pyEdge_Rank = 2;
  PyArrayObject *capi_pyEdge_tmp = NULL;
  int capi_pyEdge_intent = 0;
  PyObject *pyEdge_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  double *pyDiff = NULL;
  npy_intp pyDiff_Dims[1] = {-1};
  const int pyDiff_Rank = 1;
  PyArrayObject *capi_pyDiff_tmp = NULL;
  int capi_pyDiff_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pySc","pyZ","pyBord","pyNgbs","pyEdge","pyDist","pyGIDs","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|OO:sfd.diffusionnl",\
    capi_kwlist,&pySc_capi,&pyZ_capi,&pyBord_capi,&pyNgbs_capi,&pyEdge_capi,&pyDist_capi,&pyGIDs_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pySc */
  pySc_Dims[0]=1;
  capi_pySc_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pySc_tmp = array_from_pyobj(NPY_DOUBLE,pySc_Dims,pySc_Rank,capi_pySc_intent,pySc_capi);
  if (capi_pySc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pySc' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pySc = (double *)(PyArray_DATA(capi_pySc_tmp));

  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 7th argument `pyGIDs' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyNgbs' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.diffusionnl() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.diffusionnl() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 6th argument `pyDist' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyZ' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

  /* Processing variable pyDiff */
  pyDiff_Dims[0]=pyglobalNb;
  capi_pyDiff_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyDiff_tmp = array_from_pyobj(NPY_DOUBLE,pyDiff_Dims,pyDiff_Rank,capi_pyDiff_intent,Py_None);
  if (capi_pyDiff_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyDiff' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pyDiff = (double *)(PyArray_DATA(capi_pyDiff_tmp));

  /* Processing variable pyBord */
  pyBord_Dims[0]=pyglobalNb;
  capi_pyBord_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyBord_tmp = array_from_pyobj(NPY_INT,pyBord_Dims,pyBord_Rank,capi_pyBord_intent,pyBord_capi);
  if (capi_pyBord_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyBord' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pyBord = (int *)(PyArray_DATA(capi_pyBord_tmp));

  /* Processing variable pyEdge */
  pyEdge_Dims[0]=pyglobalNb,pyEdge_Dims[1]=20;
  capi_pyEdge_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyEdge_tmp = array_from_pyobj(NPY_DOUBLE,pyEdge_Dims,pyEdge_Rank,capi_pyEdge_intent,pyEdge_capi);
  if (capi_pyEdge_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyEdge' of sfd.diffusionnl to C/Fortran array" );
  } else {
    pyEdge = (double *)(PyArray_DATA(capi_pyEdge_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pySc,pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,pyDiff,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_pyDiff_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_pyEdge_tmp!=pyEdge_capi) {
    Py_XDECREF(capi_pyEdge_tmp); }
  }  /*if (capi_pyEdge_tmp == NULL) ... else of pyEdge*/
  /* End of cleaning variable pyEdge */
  if((PyObject *)capi_pyBord_tmp!=pyBord_capi) {
    Py_XDECREF(capi_pyBord_tmp); }
  }  /*if (capi_pyBord_tmp == NULL) ... else of pyBord*/
  /* End of cleaning variable pyBord */
  }  /*if (capi_pyDiff_tmp == NULL) ... else of pyDiff*/
  /* End of cleaning variable pyDiff */
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
  if((PyObject *)capi_pySc_tmp!=pySc_capi) {
    Py_XDECREF(capi_pySc_tmp); }
  }  /*if (capi_pySc_tmp == NULL) ... else of pySc*/
  /* End of cleaning variable pySc */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of diffusionnl *****************************/

/******************************** diffusionero ********************************/
static char doc_f2py_rout_sfd_diffusionero[] = "\
pyEro = diffusionero(pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,[pylocalNb,pyglobalNb])\n\nWrapper for ``diffusionero``.\
\n\nParameters\n----------\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyBord : input rank-1 array('i') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyEdge : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyEro : rank-1 array('d') with bounds (pyglobalNb)";
/* extern void diffusionero(double*,int*,int*,double*,double*,int*,double*,int,int); */
static PyObject *f2py_rout_sfd_diffusionero(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,double*,int*,double*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyBord = NULL;
  npy_intp pyBord_Dims[1] = {-1};
  const int pyBord_Rank = 1;
  PyArrayObject *capi_pyBord_tmp = NULL;
  int capi_pyBord_intent = 0;
  PyObject *pyBord_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyEdge = NULL;
  npy_intp pyEdge_Dims[2] = {-1, -1};
  const int pyEdge_Rank = 2;
  PyArrayObject *capi_pyEdge_tmp = NULL;
  int capi_pyEdge_intent = 0;
  PyObject *pyEdge_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  double *pyEro = NULL;
  npy_intp pyEro_Dims[1] = {-1};
  const int pyEro_Rank = 1;
  PyArrayObject *capi_pyEro_tmp = NULL;
  int capi_pyEro_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pyZ","pyBord","pyNgbs","pyEdge","pyDist","pyGIDs","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OO:sfd.diffusionero",\
    capi_kwlist,&pyZ_capi,&pyBord_capi,&pyNgbs_capi,&pyEdge_capi,&pyDist_capi,&pyGIDs_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 6th argument `pyGIDs' of sfd.diffusionero to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyNgbs' of sfd.diffusionero to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.diffusionero() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.diffusionero() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pyZ' of sfd.diffusionero to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

  /* Processing variable pyBord */
  pyBord_Dims[0]=pyglobalNb;
  capi_pyBord_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyBord_tmp = array_from_pyobj(NPY_INT,pyBord_Dims,pyBord_Rank,capi_pyBord_intent,pyBord_capi);
  if (capi_pyBord_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyBord' of sfd.diffusionero to C/Fortran array" );
  } else {
    pyBord = (int *)(PyArray_DATA(capi_pyBord_tmp));

  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyDist' of sfd.diffusionero to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyEdge */
  pyEdge_Dims[0]=pyglobalNb,pyEdge_Dims[1]=20;
  capi_pyEdge_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyEdge_tmp = array_from_pyobj(NPY_DOUBLE,pyEdge_Dims,pyEdge_Rank,capi_pyEdge_intent,pyEdge_capi);
  if (capi_pyEdge_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyEdge' of sfd.diffusionero to C/Fortran array" );
  } else {
    pyEdge = (double *)(PyArray_DATA(capi_pyEdge_tmp));

  /* Processing variable pyEro */
  pyEro_Dims[0]=pyglobalNb;
  capi_pyEro_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyEro_tmp = array_from_pyobj(NPY_DOUBLE,pyEro_Dims,pyEro_Rank,capi_pyEro_intent,Py_None);
  if (capi_pyEro_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyEro' of sfd.diffusionero to C/Fortran array" );
  } else {
    pyEro = (double *)(PyArray_DATA(capi_pyEro_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,pyEro,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_pyEro_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_pyEro_tmp == NULL) ... else of pyEro*/
  /* End of cleaning variable pyEro */
  if((PyObject *)capi_pyEdge_tmp!=pyEdge_capi) {
    Py_XDECREF(capi_pyEdge_tmp); }
  }  /*if (capi_pyEdge_tmp == NULL) ... else of pyEdge*/
  /* End of cleaning variable pyEdge */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  if((PyObject *)capi_pyBord_tmp!=pyBord_capi) {
    Py_XDECREF(capi_pyBord_tmp); }
  }  /*if (capi_pyBord_tmp == NULL) ... else of pyBord*/
  /* End of cleaning variable pyBord */
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of diffusionero ****************************/

/****************************** diffusionmarine ******************************/
static char doc_f2py_rout_sfd_diffusionmarine[] = "\
pyDiff = diffusionmarine(pyZ,pyBord,pyDep,pyNgbs,pyEdge,pyDist,pyGIDs,[pylocalNb,pyglobalNb])\n\nWrapper for ``diffusionmarine``.\
\n\nParameters\n----------\n"
"pyZ : input rank-1 array('d') with bounds (pyglobalNb)\n"
"pyBord : input rank-1 array('i') with bounds (pyglobalNb)\n"
"pyDep : input rank-1 array('i') with bounds (pyglobalNb)\n"
"pyNgbs : input rank-2 array('i') with bounds (pyglobalNb,20)\n"
"pyEdge : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyDist : input rank-2 array('d') with bounds (pyglobalNb,20)\n"
"pyGIDs : input rank-1 array('i') with bounds (pylocalNb)\n"
"\nOther Parameters\n----------------\n"
"pylocalNb : input int, optional\n    Default: len(pyGIDs)\n"
"pyglobalNb : input int, optional\n    Default: len(pyNgbs)\n"
"\nReturns\n-------\n"
"pyDiff : rank-1 array('d') with bounds (pyglobalNb)";
/* extern void diffusionmarine(double*,int*,int*,int*,double*,double*,int*,double*,int,int); */
static PyObject *f2py_rout_sfd_diffusionmarine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,double*,double*,int*,double*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *pyZ = NULL;
  npy_intp pyZ_Dims[1] = {-1};
  const int pyZ_Rank = 1;
  PyArrayObject *capi_pyZ_tmp = NULL;
  int capi_pyZ_intent = 0;
  PyObject *pyZ_capi = Py_None;
  int *pyBord = NULL;
  npy_intp pyBord_Dims[1] = {-1};
  const int pyBord_Rank = 1;
  PyArrayObject *capi_pyBord_tmp = NULL;
  int capi_pyBord_intent = 0;
  PyObject *pyBord_capi = Py_None;
  int *pyDep = NULL;
  npy_intp pyDep_Dims[1] = {-1};
  const int pyDep_Rank = 1;
  PyArrayObject *capi_pyDep_tmp = NULL;
  int capi_pyDep_intent = 0;
  PyObject *pyDep_capi = Py_None;
  int *pyNgbs = NULL;
  npy_intp pyNgbs_Dims[2] = {-1, -1};
  const int pyNgbs_Rank = 2;
  PyArrayObject *capi_pyNgbs_tmp = NULL;
  int capi_pyNgbs_intent = 0;
  PyObject *pyNgbs_capi = Py_None;
  double *pyEdge = NULL;
  npy_intp pyEdge_Dims[2] = {-1, -1};
  const int pyEdge_Rank = 2;
  PyArrayObject *capi_pyEdge_tmp = NULL;
  int capi_pyEdge_intent = 0;
  PyObject *pyEdge_capi = Py_None;
  double *pyDist = NULL;
  npy_intp pyDist_Dims[2] = {-1, -1};
  const int pyDist_Rank = 2;
  PyArrayObject *capi_pyDist_tmp = NULL;
  int capi_pyDist_intent = 0;
  PyObject *pyDist_capi = Py_None;
  int *pyGIDs = NULL;
  npy_intp pyGIDs_Dims[1] = {-1};
  const int pyGIDs_Rank = 1;
  PyArrayObject *capi_pyGIDs_tmp = NULL;
  int capi_pyGIDs_intent = 0;
  PyObject *pyGIDs_capi = Py_None;
  double *pyDiff = NULL;
  npy_intp pyDiff_Dims[1] = {-1};
  const int pyDiff_Rank = 1;
  PyArrayObject *capi_pyDiff_tmp = NULL;
  int capi_pyDiff_intent = 0;
  int pylocalNb = 0;
  PyObject *pylocalNb_capi = Py_None;
  int pyglobalNb = 0;
  PyObject *pyglobalNb_capi = Py_None;
  static char *capi_kwlist[] = {"pyZ","pyBord","pyDep","pyNgbs","pyEdge","pyDist","pyGIDs","pylocalNb","pyglobalNb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|OO:sfd.diffusionmarine",\
    capi_kwlist,&pyZ_capi,&pyBord_capi,&pyDep_capi,&pyNgbs_capi,&pyEdge_capi,&pyDist_capi,&pyGIDs_capi,&pylocalNb_capi,&pyglobalNb_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pyGIDs */
  ;
  capi_pyGIDs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyGIDs_tmp = array_from_pyobj(NPY_INT,pyGIDs_Dims,pyGIDs_Rank,capi_pyGIDs_intent,pyGIDs_capi);
  if (capi_pyGIDs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 7th argument `pyGIDs' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyGIDs = (int *)(PyArray_DATA(capi_pyGIDs_tmp));

  /* Processing variable pyNgbs */
  pyNgbs_Dims[1]=20;
  capi_pyNgbs_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyNgbs_tmp = array_from_pyobj(NPY_INT,pyNgbs_Dims,pyNgbs_Rank,capi_pyNgbs_intent,pyNgbs_capi);
  if (capi_pyNgbs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 4th argument `pyNgbs' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyNgbs = (int *)(PyArray_DATA(capi_pyNgbs_tmp));

  /* Processing variable pyglobalNb */
  if (pyglobalNb_capi == Py_None) pyglobalNb = len(pyNgbs); else
    f2py_success = int_from_pyobj(&pyglobalNb,pyglobalNb_capi,"sfd.diffusionmarine() 2nd keyword (pyglobalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pylocalNb */
  if (pylocalNb_capi == Py_None) pylocalNb = len(pyGIDs); else
    f2py_success = int_from_pyobj(&pylocalNb,pylocalNb_capi,"sfd.diffusionmarine() 1st keyword (pylocalNb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pyDep */
  pyDep_Dims[0]=pyglobalNb;
  capi_pyDep_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDep_tmp = array_from_pyobj(NPY_INT,pyDep_Dims,pyDep_Rank,capi_pyDep_intent,pyDep_capi);
  if (capi_pyDep_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 3rd argument `pyDep' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyDep = (int *)(PyArray_DATA(capi_pyDep_tmp));

  /* Processing variable pyBord */
  pyBord_Dims[0]=pyglobalNb;
  capi_pyBord_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyBord_tmp = array_from_pyobj(NPY_INT,pyBord_Dims,pyBord_Rank,capi_pyBord_intent,pyBord_capi);
  if (capi_pyBord_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 2nd argument `pyBord' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyBord = (int *)(PyArray_DATA(capi_pyBord_tmp));

  /* Processing variable pyDist */
  pyDist_Dims[0]=pyglobalNb,pyDist_Dims[1]=20;
  capi_pyDist_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyDist_tmp = array_from_pyobj(NPY_DOUBLE,pyDist_Dims,pyDist_Rank,capi_pyDist_intent,pyDist_capi);
  if (capi_pyDist_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 6th argument `pyDist' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyDist = (double *)(PyArray_DATA(capi_pyDist_tmp));

  /* Processing variable pyEdge */
  pyEdge_Dims[0]=pyglobalNb,pyEdge_Dims[1]=20;
  capi_pyEdge_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyEdge_tmp = array_from_pyobj(NPY_DOUBLE,pyEdge_Dims,pyEdge_Rank,capi_pyEdge_intent,pyEdge_capi);
  if (capi_pyEdge_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 5th argument `pyEdge' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyEdge = (double *)(PyArray_DATA(capi_pyEdge_tmp));

  /* Processing variable pyZ */
  pyZ_Dims[0]=pyglobalNb;
  capi_pyZ_intent |= F2PY_INTENT_C|F2PY_INTENT_IN;
  capi_pyZ_tmp = array_from_pyobj(NPY_DOUBLE,pyZ_Dims,pyZ_Rank,capi_pyZ_intent,pyZ_capi);
  if (capi_pyZ_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting 1st argument `pyZ' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyZ = (double *)(PyArray_DATA(capi_pyZ_tmp));

  /* Processing variable pyDiff */
  pyDiff_Dims[0]=pyglobalNb;
  capi_pyDiff_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_C|F2PY_INTENT_OUT;
  capi_pyDiff_tmp = array_from_pyobj(NPY_DOUBLE,pyDiff_Dims,pyDiff_Rank,capi_pyDiff_intent,Py_None);
  if (capi_pyDiff_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sfd_error,"failed in converting hidden `pyDiff' of sfd.diffusionmarine to C/Fortran array" );
  } else {
    pyDiff = (double *)(PyArray_DATA(capi_pyDiff_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(pyZ,pyBord,pyDep,pyNgbs,pyEdge,pyDist,pyGIDs,pyDiff,pylocalNb,pyglobalNb);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_pyDiff_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_pyDiff_tmp == NULL) ... else of pyDiff*/
  /* End of cleaning variable pyDiff */
  if((PyObject *)capi_pyZ_tmp!=pyZ_capi) {
    Py_XDECREF(capi_pyZ_tmp); }
  }  /*if (capi_pyZ_tmp == NULL) ... else of pyZ*/
  /* End of cleaning variable pyZ */
  if((PyObject *)capi_pyEdge_tmp!=pyEdge_capi) {
    Py_XDECREF(capi_pyEdge_tmp); }
  }  /*if (capi_pyEdge_tmp == NULL) ... else of pyEdge*/
  /* End of cleaning variable pyEdge */
  if((PyObject *)capi_pyDist_tmp!=pyDist_capi) {
    Py_XDECREF(capi_pyDist_tmp); }
  }  /*if (capi_pyDist_tmp == NULL) ... else of pyDist*/
  /* End of cleaning variable pyDist */
  if((PyObject *)capi_pyBord_tmp!=pyBord_capi) {
    Py_XDECREF(capi_pyBord_tmp); }
  }  /*if (capi_pyBord_tmp == NULL) ... else of pyBord*/
  /* End of cleaning variable pyBord */
  if((PyObject *)capi_pyDep_tmp!=pyDep_capi) {
    Py_XDECREF(capi_pyDep_tmp); }
  }  /*if (capi_pyDep_tmp == NULL) ... else of pyDep*/
  /* End of cleaning variable pyDep */
  } /*if (f2py_success) of pylocalNb*/
  /* End of cleaning variable pylocalNb */
  } /*if (f2py_success) of pyglobalNb*/
  /* End of cleaning variable pyglobalNb */
  if((PyObject *)capi_pyNgbs_tmp!=pyNgbs_capi) {
    Py_XDECREF(capi_pyNgbs_tmp); }
  }  /*if (capi_pyNgbs_tmp == NULL) ... else of pyNgbs*/
  /* End of cleaning variable pyNgbs */
  if((PyObject *)capi_pyGIDs_tmp!=pyGIDs_capi) {
    Py_XDECREF(capi_pyGIDs_tmp); }
  }  /*if (capi_pyGIDs_tmp == NULL) ... else of pyGIDs*/
  /* End of cleaning variable pyGIDs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of diffusionmarine ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"dirview",-1,{{-1}},0,(char *)dirview,(f2py_init_func)f2py_rout_sfd_dirview,doc_f2py_rout_sfd_dirview},
  {"directions",-1,{{-1}},0,(char *)directions,(f2py_init_func)f2py_rout_sfd_directions,doc_f2py_rout_sfd_directions},
  {"directions_base",-1,{{-1}},0,(char *)directions_base,(f2py_init_func)f2py_rout_sfd_directions_base,doc_f2py_rout_sfd_directions_base},
  {"diffusion",-1,{{-1}},0,(char *)diffusion,(f2py_init_func)f2py_rout_sfd_diffusion,doc_f2py_rout_sfd_diffusion},
  {"diffnlcfl",-1,{{-1}},0,(char *)diffnlcfl,(f2py_init_func)f2py_rout_sfd_diffnlcfl,doc_f2py_rout_sfd_diffnlcfl},
  {"diffusionnl",-1,{{-1}},0,(char *)diffusionnl,(f2py_init_func)f2py_rout_sfd_diffusionnl,doc_f2py_rout_sfd_diffusionnl},
  {"diffusionero",-1,{{-1}},0,(char *)diffusionero,(f2py_init_func)f2py_rout_sfd_diffusionero,doc_f2py_rout_sfd_diffusionero},
  {"diffusionmarine",-1,{{-1}},0,(char *)diffusionmarine,(f2py_init_func)f2py_rout_sfd_diffusionmarine,doc_f2py_rout_sfd_diffusionmarine},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "sfd",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_sfd(void) {
#else
#define RETVAL
PyMODINIT_FUNC initsfd(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = sfd_module = PyModule_Create(&moduledef);
#else
  m = sfd_module = Py_InitModule("sfd", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module sfd (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'sfd' is auto-generated with f2py (version:2).\nFunctions:\n"
"  pyBase,pyRcv = dirview(pyElev,pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,sealimit,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
"  pyBase,pyRcv,pyMaxh,pyMaxDep = directions(pyElev,pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
"  pyBase,pyRcv = directions_base(pyZ,pyNgbs,pyEdge,pyDist,pyGIDs,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
"  pyDiff = diffusion(pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
"  pyCFL = diffnlcfl(pySc,pyKd,pyZ,pyBord,pyNgbs,pyDist,pyGIDs,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
"  pyDiff = diffusionnl(pySc,pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
"  pyEro = diffusionero(pyZ,pyBord,pyNgbs,pyEdge,pyDist,pyGIDs,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
"  pyDiff = diffusionmarine(pyZ,pyBord,pyDep,pyNgbs,pyEdge,pyDist,pyGIDs,pylocalNb=len(pyGIDs),pyglobalNb=len(pyNgbs))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  sfd_error = PyErr_NewException ("sfd.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"sfd");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
