name: badlands
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.12
  - numpy<2
  - pip
  - pandas
  - scipy
  - compilers
  - gfortran
  - git-lfs
  - h5py
  - matplotlib
  - pip:
      - gFlex
